# Generated by Django 5.2.15 on 2026-08-07 18:42

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import tournament.diplomacy.tasks.validate_sc_count
import tournament.models
import tournament.players.player
import tournament.wdd
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("tournament", "0001_initial"),
        ("tournament", "0002_auto_20161118_1312"),
        ("tournament", "0003_auto_20171025_1549"),
    ]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GameSet",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
                (
                    "initial_image",
                    models.ImageField(upload_to=tournament.models.game_image_location),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GreatPower",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
                ("abbreviation", models.CharField(max_length=1, unique=True)),
                ("starting_centres", models.PositiveIntegerField()),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                (
                    "wdd_player_id",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        unique=True,
                        validators=[tournament.wdd.validate_wdd_player_id],
                        verbose_name="WDD player id",
                    ),
                ),
                (
                    "picture",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=tournament.players.player.player_picture_location,
                    ),
                ),
            ],
            options={
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="Round",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scoring_system",
                    models.CharField(
                        choices=[
                            ("CDiplo 100", "CDiplo 100"),
                            ("CDiplo 80", "CDiplo 80"),
                            ("Draw size", "Draw size"),
                            ("Solo or bust", "Solo or bust"),
                            ("Sum of Squares", "Sum of Squares"),
                        ],
                        help_text="How to calculate a score for one game",
                        max_length=40,
                        verbose_name="Game scoring system",
                    ),
                ),
                (
                    "dias",
                    models.BooleanField(verbose_name="Draws Include All Survivors"),
                ),
                ("start", models.DateTimeField()),
                (
                    "final_year",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1901)],
                    ),
                ),
                ("earliest_end_time", models.DateTimeField(blank=True, null=True)),
                ("latest_end_time", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["start"],
            },
        ),
        migrations.CreateModel(
            name="RoundPlayer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField(default=0.0)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tournament.player",
                    ),
                ),
                (
                    "the_round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tournament.round",
                        verbose_name="round",
                    ),
                ),
            ],
            options={
                "ordering": ["player"],
            },
        ),
        migrations.CreateModel(
            name="Tournament",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "tournament_scoring_system",
                    models.CharField(
                        choices=[
                            ("Sum best 2 rounds", "Sum best 2 rounds"),
                            ("Sum best 3 rounds", "Sum best 3 rounds"),
                            ("Sum best 4 rounds", "Sum best 4 rounds"),
                        ],
                        help_text="How to combine round scores into a tournament score",
                        max_length=40,
                    ),
                ),
                (
                    "round_scoring_system",
                    models.CharField(
                        choices=[("Best game counts", "Best game counts")],
                        help_text="How to combine game scores into a round score",
                        max_length=40,
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the tournament is visible to all site visitors",
                    ),
                ),
                (
                    "managers",
                    models.ManyToManyField(
                        help_text="Which users can modify the tournament,<br/> and see it while it is unpublished.<br/>",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.AddField(
            model_name="round",
            name="tournament",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tournament.tournament"
            ),
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Must be unique within the tournament. No spaces",
                        max_length=20,
                        validators=[tournament.models.validate_game_name],
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_finished", models.BooleanField(default=False)),
                ("is_top_board", models.BooleanField(default=False)),
                (
                    "power_assignment",
                    models.CharField(
                        choices=[("R", "Random"), ("F", "French method")],
                        default="R",
                        max_length=1,
                        verbose_name="Power assignment method",
                    ),
                ),
                (
                    "the_round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tournament.round",
                        verbose_name="round",
                    ),
                ),
                (
                    "the_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tournament.gameset",
                        verbose_name="set",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SetPower",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("colour", models.CharField(max_length=20)),
                (
                    "power",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tournament.greatpower",
                    ),
                ),
                (
                    "the_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tournament.gameset",
                        verbose_name="set",
                    ),
                ),
            ],
            options={
                "unique_together": {("the_set", "power")},
            },
        ),
        migrations.CreateModel(
            name="CentreCount",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1900)]
                    ),
                ),
                (
                    "count",
                    models.PositiveSmallIntegerField(
                        validators=[
                            tournament.diplomacy.tasks.validate_sc_count.validate_sc_count
                        ]
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tournament.game",
                    ),
                ),
                (
                    "power",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="tournament.greatpower",
                    ),
                ),
            ],
            options={
                "ordering": ["game", "year"],
                "unique_together": {("power", "game", "year")},
            },
        ),
        migrations.CreateModel(
            name="PlayerRanking",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tournament", models.CharField(max_length=40)),
                ("position", models.PositiveSmallIntegerField()),
                ("year", models.PositiveSmallIntegerField()),
                ("date", models.DateField(blank=True, null=True)),
                ("title", models.CharField(blank=True, max_length=30)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tournament.player",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DrawProposal",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1901)]
                    ),
                ),
                (
                    "season",
                    models.CharField(
                        choices=[("S", "spring"), ("F", "fall")], max_length=1
                    ),
                ),
                ("passed", models.BooleanField()),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tournament.game",
                    ),
                ),
                (
                    "power_1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="tournament.greatpower",
                    ),
                ),
                (
                    "power_2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="tournament.greatpower",
                    ),
                ),
                (
                    "power_3",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="tournament.greatpower",
                    ),
                ),
                (
                    "power_4",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="tournament.greatpower",
                    ),
                ),
                (
                    "power_5",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="tournament.greatpower",
                    ),
                ),
                (
                    "power_6",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="tournament.greatpower",
                    ),
                ),
                (
                    "power_7",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="tournament.greatpower",
                    ),
                ),
                (
                    "proposer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="tournament.greatpower",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GameImage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1901)]
                    ),
                ),
                (
                    "season",
                    models.CharField(
                        choices=[("S", "spring"), ("F", "fall")],
                        default="S",
                        max_length=1,
                    ),
                ),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("M", "movement"),
                            ("R", "retreats"),
                            ("X", "adjustments"),
                        ],
                        default="M",
                        max_length=1,
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to=tournament.models.game_image_location),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tournament.game",
                    ),
                ),
            ],
            options={
                "ordering": ["game", "year", "-season", "phase"],
                "unique_together": {("game", "year", "season", "phase")},
            },
        ),
        migrations.CreateModel(
            name="GamePlayer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_year",
                    models.PositiveSmallIntegerField(
                        default=1901,
                        validators=[django.core.validators.MinValueValidator(1901)],
                    ),
                ),
                (
                    "first_season",
                    models.CharField(
                        choices=[("S", "spring"), ("F", "fall")],
                        default="S",
                        max_length=1,
                    ),
                ),
                (
                    "last_year",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1901)],
                    ),
                ),
                (
                    "last_season",
                    models.CharField(
                        blank=True,
                        choices=[("S", "spring"), ("F", "fall")],
                        max_length=1,
                    ),
                ),
                ("score", models.FloatField(default=0.0)),
                ("power_choice_order", models.PositiveSmallIntegerField(default=1)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tournament.game",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tournament.player",
                    ),
                ),
                (
                    "power",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="tournament.greatpower",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlayerGameResult",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tournament_name", models.CharField(max_length=40)),
                ("game_name", models.CharField(max_length=20)),
                ("date", models.DateField()),
                ("position", models.PositiveSmallIntegerField()),
                (
                    "position_equals",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("score", models.FloatField(blank=True, null=True)),
                (
                    "final_sc_count",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "result",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("W", "Win"),
                            ("D2", "2-way draw"),
                            ("D3", "3-way draw"),
                            ("D4", "4-way draw"),
                            ("D5", "5-way draw"),
                            ("D6", "6-way draw"),
                            ("D7", "7-way draw"),
                            ("L", "Loss"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "year_eliminated",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1901)],
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tournament.player",
                    ),
                ),
                (
                    "power",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="tournament.greatpower",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("tournament_name", "game_name", "player", "power")
                },
            },
        ),
        migrations.CreateModel(
            name="TournamentPlayer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField(default=0.0)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tournament.player",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tournament.tournament",
                    ),
                ),
            ],
            options={
                "ordering": ["player"],
                "unique_together": {("player", "tournament")},
            },
        ),
        migrations.CreateModel(
            name="PlayerAward",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tournament", models.CharField(max_length=40)),
                ("date", models.DateField()),
                ("name", models.CharField(max_length=50)),
                ("score", models.FloatField(blank=True, null=True)),
                (
                    "final_sc_count",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tournament.player",
                    ),
                ),
                (
                    "power",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="tournament.greatpower",
                    ),
                ),
            ],
            options={
                "unique_together": {("player", "tournament", "date", "name")},
            },
        ),
    ]
