# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 22:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_auto_20161118_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerAward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament', models.CharField(max_length=40)),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=50)),
                ('score', models.FloatField(blank=True, null=True)),
                ('final_sc_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.Player')),
                ('power', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tournament.GreatPower')),
            ],
        ),
        migrations.AlterField(
            model_name='drawproposal',
            name='season',
            field=models.CharField(choices=[('S', 'spring'), ('F', 'fall')], max_length=1),
        ),
        migrations.AlterField(
            model_name='game',
            name='power_assignment',
            field=models.CharField(choices=[('R', 'Random'), ('F', 'French method')], default='R', max_length=1, verbose_name='Power assignment method'),
        ),
        migrations.AlterField(
            model_name='gameimage',
            name='phase',
            field=models.CharField(choices=[('M', 'movement'), ('R', 'retreats'), ('X', 'adjustments')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='gameimage',
            name='season',
            field=models.CharField(choices=[('S', 'spring'), ('F', 'fall')], default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='gameplayer',
            name='first_season',
            field=models.CharField(choices=[('S', 'spring'), ('F', 'fall')], default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='gameplayer',
            name='last_season',
            field=models.CharField(blank=True, choices=[('S', 'spring'), ('F', 'fall')], max_length=1),
        ),
        migrations.AlterField(
            model_name='playergameresult',
            name='result',
            field=models.CharField(blank=True, choices=[('W', 'Win'), ('D2', '2-way draw'), ('D3', '3-way draw'), ('D4', '4-way draw'), ('D5', '5-way draw'), ('D6', '6-way draw'), ('D7', '7-way draw'), ('L', 'Loss')], max_length=2),
        ),
        migrations.AlterUniqueTogether(
            name='tournamentplayer',
            unique_together=set([('player', 'tournament')]),
        ),
        migrations.AlterUniqueTogether(
            name='playeraward',
            unique_together=set([('player', 'tournament', 'date', 'name')]),
        ),
    ]
