# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 17:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_auto_20171101_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerRanking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(max_length=50)),
                ('score', models.FloatField(blank=True, null=True)),
                ('international_rank', models.CharField(max_length=20)),
                ('national_rank', models.CharField(max_length=20)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.Player')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='playerranking',
            unique_together=set([('player', 'system')]),
        ),
    ]
