# Generated by Django 5.2.15 on 2026-08-07 18:42

import django.core.validators
import django.db.models.deletion
import tournament.diplomacy.tasks.validate_ranking
import tournament.diplomacy.utils.game_image_location
import tournament.models
import tournament.wdd
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("tournament", "0005_auto_20171101_1049"),
        ("tournament", "0006_auto_20171116_2135"),
        ("tournament", "0007_auto_20180110_2129"),
        ("tournament", "0008_auto_20180113_1147"),
        ("tournament", "0009_auto_20180113_1309"),
        ("tournament", "0010_remove_greatpower_starting_centres"),
        ("tournament", "0011_auto_20180116_1958"),
        ("tournament", "0012_tournament_wdd_tournament_id"),
        ("tournament", "0013_tournamentplayer_unranked"),
        ("tournament", "0014_auto_20180706_2058"),
        ("tournament", "0015_tournament_seed_games"),
        ("tournament", "0016_roundplayer_game_count"),
        ("tournament", "0017_auto_20180803_1320"),
        ("tournament", "0018_auto_20180803_1324"),
        ("tournament", "0019_auto_20181010_1558"),
        ("tournament", "0020_auto_20190105_1228"),
        ("tournament", "0021_auto_20190105_1230"),
        ("tournament", "0022_auto_20190131_1243"),
        ("tournament", "0023_tournament_editable"),
        ("tournament", "0024_player_email"),
        ("tournament", "0025_tournamentplayer_uuid_str"),
        ("tournament", "0026_player__wdd_name"),
        ("tournament", "0027_player_user"),
        ("tournament", "0028_tournament_best_country_criterion"),
        ("tournament", "0029_auto_20200129_2117"),
        ("tournament", "0030_auto_20200129_2117"),
        ("tournament", "0031_auto_20200130_1733"),
        ("tournament", "0032_auto_20200131_1549"),
        ("tournament", "0033_game_notes"),
        ("tournament", "0034_auto_20200813_2043"),
        ("tournament", "0035_auto_20200818_2059"),
        ("tournament", "0036_auto_20200818_2100"),
        ("tournament", "0037_auto_20200824_2350"),
        ("tournament", "0038_auto_20200902_1521"),
        ("tournament", "0039_auto_20201024_2052"),
        ("tournament", "0040_auto_20201211_1432"),
        ("tournament", "0041_tournament_no_email"),
        ("tournament", "0042_auto_20210205_1846"),
        ("tournament", "0043_auto_20210205_2117"),
        ("tournament", "0044_auto_20210207_1522"),
        ("tournament", "0045_auto_20210209_1914"),
        ("tournament", "0046_auto_20210209_1937"),
        ("tournament", "0047_auto_20210211_1958"),
        ("tournament", "0048_auto_20210326_1748"),
        ("tournament", "0049_auto_20210326_1750"),
        ("tournament", "0050_auto_20210418_2243"),
        ("tournament", "0051_auto_20210508_1114"),
        ("tournament", "0052_auto_20210511_1109"),
        ("tournament", "0053_auto_20210517_2246"),
        ("tournament", "0054_gameplayer_after_action_report"),
        ("tournament", "0055_auto_20210701_1538"),
        ("tournament", "0056_player_backstabbr_profile_url"),
        ("tournament", "0057_roundplayer_standby"),
        ("tournament", "0058_auto_20211112_1153"),
        ("tournament", "0059_auto_20211112_1155"),
        ("tournament", "0060_auto_20220328_1904"),
        ("tournament", "0061_remove_seederbias_weight"),
        ("tournament", "0062_auto_20220403_1535"),
        ("tournament", "0063_auto_20220415_2159"),
        ("tournament", "0064_auto_20220724_0951"),
        ("tournament", "0064_auto_20220425_2154"),
        ("tournament", "0065_merge_20220916_1809"),
        ("tournament", "0066_auto_20221001_1208"),
        ("tournament", "0067_tournament_delay_game_url_publication"),
        ("tournament", "0068_auto_20221001_1340"),
        ("tournament", "0069_auto_20221001_1342"),
        ("tournament", "0070_game_notes"),
        ("tournament", "0071_series"),
        ("tournament", "0072_auto_20221014_1802"),
        ("tournament", "0073_drawproposal_drawing_powers"),
    ]

    dependencies = [
        ("tournament", "0004_auto_20171101_1048"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerRanking",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("system", models.CharField(max_length=50)),
                ("score", models.FloatField(blank=True, null=True)),
                ("international_rank", models.CharField(max_length=20)),
                ("national_rank", models.CharField(max_length=20)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tournament.player",
                    ),
                ),
            ],
            options={
                "unique_together": {("player", "system")},
            },
        ),
        migrations.AddField(
            model_name="drawproposal",
            name="votes_in_favour",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[tournament.models.validate_vote_count],
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="draw_secrecy",
            field=models.CharField(
                choices=[("S", "Pass/Fail"), ("C", "Numbers for and against")],
                default="S",
                max_length=1,
                verbose_name="What players are told about failed draw votes",
            ),
        ),
        migrations.AlterField(
            model_name="drawproposal",
            name="passed",
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name="playeraward",
            name="tournament",
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name="playergameresult",
            name="tournament_name",
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name="playertournamentranking",
            name="tournament",
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="name",
            field=models.CharField(max_length=60),
        ),
        migrations.CreateModel(
            name="SupplyCentre",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
                ("abbreviation", models.CharField(max_length=4, unique=True)),
                (
                    "initial_owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tournament.greatpower",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.RemoveField(
            model_name="greatpower",
            name="starting_centres",
        ),
        migrations.AddField(
            model_name="playeraward",
            name="wdd_tournament_id",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[tournament.wdd.validate_wdd_tournament_id],
                verbose_name="WDD tournament id",
            ),
        ),
        migrations.AddField(
            model_name="playergameresult",
            name="wdd_tournament_id",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[tournament.wdd.validate_wdd_tournament_id],
                verbose_name="WDD tournament id",
            ),
        ),
        migrations.AddField(
            model_name="playertournamentranking",
            name="wdd_tournament_id",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[tournament.wdd.validate_wdd_tournament_id],
                verbose_name="WDD tournament id",
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="wdd_tournament_id",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Add this after the tournament is complete and results have been uploaded to the WDD",
                null=True,
                validators=[tournament.wdd.validate_wdd_tournament_id],
                verbose_name="This tournament's id in the WDD",
            ),
        ),
        migrations.AddField(
            model_name="tournamentplayer",
            name="unranked",
            field=models.BooleanField(
                default=False,
                help_text="Set this to ignore this player when determining rankings",
                verbose_name="Ineligible for awards",
            ),
        ),
        migrations.AlterField(
            model_name="gameplayer",
            name="power",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="tournament.greatpower",
            ),
        ),
        migrations.AddField(
            model_name="roundplayer",
            name="game_count",
            field=models.PositiveIntegerField(
                default=1, help_text="number of games being played this round"
            ),
        ),
        migrations.RemoveField(
            model_name="game",
            name="power_assignment",
        ),
        migrations.RemoveField(
            model_name="gameplayer",
            name="power_choice_order",
        ),
        migrations.AddField(
            model_name="player",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="tournamentplayer",
            name="uuid_str",
            field=models.CharField(blank=True, max_length=36),
        ),
        migrations.AddField(
            model_name="player",
            name="_wdd_name",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="tournament",
            name="best_country_criterion",
            field=models.CharField(
                choices=[("S", "Highest score"), ("D", "Highest centre count")],
                default="S",
                max_length=1,
                verbose_name="How Best Country awards are determined",
            ),
        ),
        migrations.AlterField(
            model_name="drawproposal",
            name="proposer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="tournament.greatpower",
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="user",
            field=models.OneToOneField(
                blank=True,
                help_text="If the Player has an account on the site, record it here",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="editable",
            field=models.BooleanField(
                default=True,
                help_text="Uncheck to disallow any further changes to the tournament",
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="format",
            field=models.CharField(
                choices=[("F", "Face to Face"), ("V", "Virtual Face to Face")],
                default="F",
                max_length=1,
            ),
        ),
        migrations.AlterModelOptions(
            name="roundplayer",
            options={"ordering": ["player", "the_round__start"]},
        ),
        migrations.AddField(
            model_name="round",
            name="email_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="round",
            name="enable_check_in",
            field=models.BooleanField(
                default=False, verbose_name="Enable self-check-ins"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="round",
            unique_together={("tournament", "start")},
        ),
        migrations.AddField(
            model_name="player",
            name="backstabbr_username",
            field=models.CharField(
                blank=True,
                help_text="Username on the backstabbr website",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="tournamentplayer",
            name="backstabbr_username",
            field=models.CharField(
                blank=True,
                help_text="Username on the backstabbr website",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="round",
            name="scoring_system",
            field=models.CharField(
                choices=[
                    ("Bangkok", "Bangkok"),
                    ("CDiplo 100", "CDiplo 100"),
                    ("CDiplo 80", "CDiplo 80"),
                    ("Carnage with dead equal", "Carnage with dead equal"),
                    (
                        "Carnage with elimination order",
                        "Carnage with elimination order",
                    ),
                    ("Center-count Carnage", "Center-count Carnage"),
                    ("Detour09", "Detour09"),
                    ("Draw size", "Draw size"),
                    ("ManorCon", "ManorCon"),
                    ("ManorCon v2", "ManorCon v2"),
                    ("Maxonian", "Maxonian"),
                    ("OMG", "OMG"),
                    ("OpenTribute", "OpenTribute"),
                    ("Original ManorCon", "Original ManorCon"),
                    ("Solo or bust", "Solo or bust"),
                    ("Sum of Squares", "Sum of Squares"),
                    ("Tribute", "Tribute"),
                    ("Whipping", "Whipping"),
                    ("World Classic", "World Classic"),
                ],
                help_text="How to calculate a score for one game",
                max_length=40,
                verbose_name="Game scoring system",
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="no_email",
            field=models.BooleanField(
                default=False,
                help_text="Check to only generate email to tournament managers",
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="power_assignment",
            field=models.CharField(
                choices=[
                    ("A", "Minimising playing the same power"),
                    ("M", "Manually by TD or at the board"),
                    ("P", "Using player preferences and ranking"),
                    ("B", "Blind auction (separate funds for each round)"),
                    ("T", "Blind auction (single pool for all rounds)"),
                ],
                default="M",
                max_length=1,
                verbose_name="How powers are assigned",
            ),
        ),
        migrations.CreateModel(
            name="PowerBid",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bid",
                    models.PositiveSmallIntegerField(
                        validators=[tournament.models.validate_bid]
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tournament.tournamentplayer",
                    ),
                ),
                (
                    "power",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tournament.greatpower",
                    ),
                ),
                (
                    "the_round",
                    models.ForeignKey(
                        default=30,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tournament.round",
                        verbose_name="round",
                    ),
                ),
            ],
            options={
                "ordering": ["player", "power"],
                "unique_together": {("player", "power", "the_round")},
            },
        ),
        migrations.AddField(
            model_name="tournament",
            name="seed_games",
            field=models.BooleanField(
                default=True,
                help_text="Check to let the software seed players to games",
            ),
        ),
        migrations.AlterModelOptions(
            name="gameplayer",
            options={"ordering": ["game", "power"]},
        ),
        migrations.RemoveField(
            model_name="gameplayer",
            name="first_season",
        ),
        migrations.RemoveField(
            model_name="gameplayer",
            name="first_year",
        ),
        migrations.RemoveField(
            model_name="gameplayer",
            name="last_season",
        ),
        migrations.RemoveField(
            model_name="gameplayer",
            name="last_year",
        ),
        migrations.AlterField(
            model_name="tournament",
            name="round_scoring_system",
            field=models.CharField(
                choices=[
                    ("Add all game scores", "Add all game scores"),
                    ("Best game counts", "Best game counts"),
                    (
                        "Best game counts. Sitters get 4005",
                        "Best game counts. Sitters get 4005",
                    ),
                    (
                        "Best game counts. Sitters get 4005 once",
                        "Best game counts. Sitters get 4005 once",
                    ),
                ],
                help_text="How to combine game scores into a round score",
                max_length=40,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="gameplayer",
            unique_together={("power", "game")},
        ),
        migrations.AlterUniqueTogether(
            name="roundplayer",
            unique_together={("player", "the_round")},
        ),
        migrations.AlterUniqueTogether(
            name="tournament",
            unique_together={("name", "start_date")},
        ),
        migrations.AddField(
            model_name="gameplayer",
            name="after_action_report",
            field=models.TextField(
                blank=True, help_text="This player's account of the game"
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="backstabbr_profile_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="roundplayer",
            name="standby",
            field=models.BooleanField(
                default=False,
                help_text="check if the player would prefer not to play this round",
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="location",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="tournament",
            name="location",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="tournamentplayer",
            name="location",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name="roundplayer",
            name="game_count",
            field=models.PositiveIntegerField(
                default=1, help_text="number of games to play this round"
            ),
        ),
        migrations.CreateModel(
            name="SeederBias",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "player1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tournament.tournamentplayer",
                    ),
                ),
                (
                    "player2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="second_seederbias_set",
                        to="tournament.tournamentplayer",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Seeder biases",
                "unique_together": {("player1", "player2")},
            },
        ),
        migrations.AddField(
            model_name="game",
            name="external_url",
            field=models.URLField(
                blank=True,
                help_text="Will be included in board call emails and game page",
                verbose_name="Backstabbr URL",
            ),
        ),
        migrations.AlterField(
            model_name="gameset",
            name="initial_image",
            field=models.ImageField(
                upload_to=tournament.diplomacy.utils.game_image_location.game_image_location
            ),
        ),
        migrations.CreateModel(
            name="Preference",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ranking",
                    models.PositiveSmallIntegerField(
                        validators=[
                            tournament.diplomacy.tasks.validate_ranking.validate_ranking
                        ]
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tournament.tournamentplayer",
                    ),
                ),
                (
                    "power",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tournament.greatpower",
                    ),
                ),
            ],
            options={
                "ordering": ["ranking"],
                "unique_together": {("player", "power"), ("player", "ranking")},
            },
        ),
        migrations.CreateModel(
            name="SupplyCentreOwnership",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1900)]
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tournament.game",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tournament.greatpower",
                    ),
                ),
                (
                    "sc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tournament.supplycentre",
                    ),
                ),
            ],
            options={
                "ordering": ["game", "year"],
                "unique_together": {("sc", "game", "year")},
            },
        ),
        migrations.AddField(
            model_name="tournament",
            name="delay_game_url_publication",
            field=models.BooleanField(
                default=False,
                help_text="Check to keep game URL secret until after the tournament completes",
                verbose_name="Delay publishing game URL",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="notes",
            field=models.CharField(
                blank=True,
                help_text="Will be included in board call emails and game page",
                max_length=120,
            ),
        ),
        migrations.CreateModel(
            name="Series",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("description", models.CharField(max_length=2000, null=True)),
                ("slug", models.SlugField(unique=True)),
                ("tournaments", models.ManyToManyField(to="tournament.tournament")),
            ],
            options={
                "ordering": ["name"],
                "verbose_name_plural": "Series",
            },
        ),
        migrations.AddField(
            model_name="drawproposal",
            name="drawing_powers",
            field=models.ManyToManyField(
                related_name="_drawproposal_drawing_powers_+",
                to="tournament.greatpower",
            ),
        ),
    ]
