# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-13 19:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tournament.diplomacy


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0007_auto_20180110_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyCentre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('abbreviation', models.CharField(max_length=4, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SupplyCentreOwnership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(validators=[tournament.diplomacy.tasks.validate_year_including_start])),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.Game')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.GreatPower')),
                ('sc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.SupplyCentre')),
            ],
            options={
                'ordering': ['game', 'year'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='supplycentreownership',
            unique_together=set([('sc', 'game', 'year')]),
        ),
    ]
