# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-13 21:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tournament.diplomacy


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0008_auto_20180113_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplycentre',
            name='initial_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tournament.GreatPower'),
        ),
    ]
