# Generated by Django 2.0 on 2018-01-15 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0009_auto_20180113_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='greatpower',
            name='starting_centres',
        ),
    ]
