# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-17 03:58
from __future__ import unicode_literals

from django.db import migrations, models
import tournament.players


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0010_remove_greatpower_starting_centres'),
    ]

    operations = [
        migrations.AddField(
            model_name='playeraward',
            name='wdd_tournament_id',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[tournament.players.validate_wdd_tournament_id], verbose_name='WDD tournament id'),
        ),
        migrations.AddField(
            model_name='playergameresult',
            name='wdd_tournament_id',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[tournament.players.validate_wdd_tournament_id], verbose_name='WDD tournament id'),
        ),
        migrations.AddField(
            model_name='playertournamentranking',
            name='wdd_tournament_id',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[tournament.players.validate_wdd_tournament_id], verbose_name='WDD tournament id'),
        ),
    ]
