# Generated by Django 2.0 on 2018-01-19 01:10

from django.db import migrations, models
import tournament.players


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0011_auto_20180116_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='wdd_tournament_id',
            field=models.PositiveIntegerField(blank=True, help_text='Add this after the tournament is complete and results have been uploaded to the WDD', null=True, validators=[tournament.players.validate_wdd_tournament_id], verbose_name="This tournament's id in the WDD"),
        ),
    ]
