# Generated by Django 2.0 on 2018-01-31 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0012_tournament_wdd_tournament_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentplayer',
            name='unranked',
            field=models.BooleanField(default=False, help_text='Set this to ignore this player when determining rankings', verbose_name='Ineligible for awards'),
        ),
    ]
