# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-07 03:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0013_tournamentplayer_unranked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameplayer',
            name='power',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tournament.GreatPower'),
        ),
        migrations.AlterField(
            model_name='gameplayer',
            name='power_choice_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
