# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-07 04:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0014_auto_20180706_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='seed_games',
            field=models.BooleanField(default=False, help_text='Check to let the software seed players to games'),
        ),
    ]
