# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-07 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0015_tournament_seed_games'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundplayer',
            name='game_count',
            field=models.PositiveIntegerField(default=1, help_text='number of games being played this round'),
        ),
    ]
