# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-03 20:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0016_roundplayer_game_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='power_assignment',
        ),
        migrations.RemoveField(
            model_name='gameplayer',
            name='power_choice_order',
        ),
    ]
