# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-03 20:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tournament.diplomacy


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0017_auto_20180803_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking', models.PositiveSmallIntegerField(validators=[tournament.diplomacy.tasks.validate_ranking])),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.TournamentPlayer')),
                ('power', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.GreatPower')),
            ],
            options={
                'ordering': ['ranking'],
            },
        ),
        migrations.AddField(
            model_name='tournament',
            name='power_assignment',
            field=models.CharField(choices=[('M', 'Manually by TD or at the board'), ('P', 'Using player preferences and ranking')], default='M', max_length=1, verbose_name='How powers are assigned'),
        ),
        migrations.AlterUniqueTogether(
            name='preference',
            unique_together=set([('player', 'ranking')]),
        ),
    ]
