# Generated by Django 2.0 on 2018-10-10 22:58

from django.db import migrations, models
import django.db.models.deletion
import tournament.models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0018_auto_20180803_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeederBias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveSmallIntegerField(help_text="Number of games to pretend they've already played together", validators=[tournament.models.validate_weight])),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.TournamentPlayer')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_seederbias_set', to='tournament.TournamentPlayer')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='seederbias',
            unique_together={('player1', 'player2')},
        ),
    ]
