# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-05 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0020_auto_20190105_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='power_assignment',
            field=models.CharField(choices=[('A', 'Minimising playing the same power'), ('M', 'Manually by TD or at the board'), ('P', 'Using player preferences and ranking')], default='M', max_length=1, verbose_name='How powers are assigned'),
        ),
    ]
