# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-31 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0022_auto_20190131_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='editable',
            field=models.BooleanField(default=True, help_text='Check to disallow any further changes to the tournament'),
        ),
    ]
