# Generated by Django 2.1.2 on 2019-02-23 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0023_tournament_editable'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
