# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-27 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0024_player_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentplayer',
            name='uuid_str',
            field=models.CharField(blank=True, max_length=36),
        ),
    ]
