# Generated by Django 2.1.7 on 2019-06-05 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0025_tournamentplayer_uuid_str'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='_wdd_name',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
