# Generated by Django 2.2 on 2019-07-07 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0027_player_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='best_country_criterion',
            field=models.CharField(choices=[('S', 'Highest score'), ('D', 'Highest centre count')], default='S', max_length=1, verbose_name='How are Best Country awards determined?'),
        ),
    ]
