# Generated by Django 2.1.2 on 2020-01-30 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0028_tournament_best_country_criterion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='scoring_system',
            field=models.CharField(choices=[('CDiplo 100', 'CDiplo 100'), ('CDiplo 80', 'CDiplo 80'), ('Carnage with dead equal', 'Carnage with dead equal'), ('Carnage with elimination order', 'Carnage with elimination order'), ('Draw size', 'Draw size'), ('Janus', 'Janus'), ('Solo or bust', 'Solo or bust'), ('Sum of Squares', 'Sum of Squares')], help_text='How to calculate a score for one game', max_length=40, verbose_name='Game scoring system'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='best_country_criterion',
            field=models.CharField(choices=[('S', 'Highest score'), ('D', 'Highest centre count')], default='S', max_length=1, verbose_name='How Best Country awards are determined'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='round_scoring_system',
            field=models.CharField(choices=[('Best game counts', 'Best game counts'), ('Best game counts. Sitters get 4005', 'Best game counts. Sitters get 4005')], help_text='How to combine game scores into a round score', max_length=40),
        ),
    ]
