# Generated by Django 2.1.2 on 2020-01-30 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0029_auto_20200129_2117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameplayer',
            options={'ordering': ['game', 'power', 'first_year']},
        ),
    ]
