# Generated by Django 2.1.2 on 2020-01-31 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0030_auto_20200129_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawproposal',
            name='proposer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tournament.GreatPower'),
        ),
    ]
