# Generated by Django 2.1.7 on 2020-01-31 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0031_auto_20200130_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='round_scoring_system',
            field=models.CharField(choices=[('Best game counts', 'Best game counts'), ('Best game counts. Sitters get 4005', 'Best game counts. Sitters get 4005'), ('Best game counts. Sitters get 4005 once', 'Best game counts. Sitters get 4005 once')], help_text='How to combine game scores into a round score', max_length=40),
        ),
    ]
