# Generated by Django 2.2 on 2020-07-28 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0032_auto_20200131_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='notes',
            field=models.CharField(blank=True, help_text='Will be included in board call emails and game page', max_length=120),
        ),
    ]
