# Generated by Django 2.2 on 2020-08-19 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0034_auto_20200813_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='scoring_system',
            field=models.CharField(choices=[('CDiplo 100', 'CDiplo 100'), ('CDiplo 80', 'CDiplo 80'), ('Carnage with dead equal', 'Carnage with dead equal'), ('Carnage with elimination order', 'Carnage with elimination order'), ('Draw size', 'Draw size'), ('Janus', 'Janus'), ('Solo or bust', 'Solo or bust'), ('Sum of Squares', 'Sum of Squares'), ('Tribute', 'Tribute')], help_text='How to calculate a score for one game', max_length=40, verbose_name='Game scoring system'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='editable',
            field=models.BooleanField(default=True, help_text='Uncheck to disallow any further changes to the tournament'),
        ),
    ]
