# Generated by Django 2.2 on 2020-08-19 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0035_auto_20200818_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='discord_username',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='tournament',
            name='format',
            field=models.CharField(choices=[('F', 'Face to Face'), ('V', 'Virtual Face to Face')], default='F', max_length=1),
        ),
        migrations.AddField(
            model_name='tournamentplayer',
            name='discord_username',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
