# Generated by Django 2.2 on 2020-09-02 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0037_auto_20200824_2350'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='round',
            unique_together={('tournament', 'start')},
        ),
    ]
