# Generated by Django 2.2.16 on 2020-10-25 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0038_auto_20200902_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='discord_username',
        ),
        migrations.RemoveField(
            model_name='tournamentplayer',
            name='discord_username',
        ),
        migrations.AddField(
            model_name='player',
            name='backstabbr_username',
            field=models.CharField(blank=True, help_text='Username on the backstabbr website', max_length=40),
        ),
        migrations.AddField(
            model_name='tournamentplayer',
            name='backstabbr_username',
            field=models.CharField(blank=True, help_text='Username on the backstabbr website', max_length=40),
        ),
    ]
