# Generated by Django 2.1.7 on 2020-12-11 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0040_auto_20201211_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='no_email',
            field=models.BooleanField(default=False, help_text='Check to only generate email to tournament managers'),
        ),
    ]
