# Generated by Django 2.2.16 on 2021-02-07 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0043_auto_20210205_2117'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='powerbid',
            unique_together={('player', 'bid')},
        ),
    ]
