# Generated by Django 2.2.16 on 2021-02-10 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0045_auto_20210209_1914'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='powerbid',
            unique_together={('player', 'bid', 'the_round'), ('player', 'power', 'the_round')},
        ),
        migrations.AlterUniqueTogether(
            name='preference',
            unique_together={('player', 'ranking'), ('player', 'power')},
        ),
    ]
