# Generated by Django 2.2.16 on 2021-04-19 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0049_auto_20210326_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='seed_games',
            field=models.BooleanField(default=True, help_text='Check to let the software seed players to games'),
        ),
    ]
