# Generated by Django 2.2.16 on 2021-05-08 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0050_auto_20210418_2243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameplayer',
            options={'ordering': ['game', 'power']},
        ),
        migrations.RemoveField(
            model_name='gameplayer',
            name='first_season',
        ),
        migrations.RemoveField(
            model_name='gameplayer',
            name='first_year',
        ),
        migrations.RemoveField(
            model_name='gameplayer',
            name='last_season',
        ),
        migrations.RemoveField(
            model_name='gameplayer',
            name='last_year',
        ),
    ]
