# Generated by Django 2.2.16 on 2021-05-18 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0052_auto_20210511_1109'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gameplayer',
            unique_together={('power', 'game')},
        ),
        migrations.AlterUniqueTogether(
            name='roundplayer',
            unique_together={('player', 'the_round')},
        ),
        migrations.AlterUniqueTogether(
            name='tournament',
            unique_together={('name', 'start_date')},
        ),
    ]
