# Generated by Django 2.2.16 on 2021-05-18 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0053_auto_20210517_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplayer',
            name='after_action_report',
            field=models.TextField(blank=True, help_text="This player's account of the game"),
        ),
    ]
