# Generated by Django 2.2.16 on 2021-07-01 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0055_auto_20210701_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='backstabbr_profile_url',
            field=models.URLField(blank=True),
        ),
    ]
