# Generated by Django 2.2 on 2021-11-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0058_auto_20211112_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='location',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='tournament',
            name='location',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='tournamentplayer',
            name='location',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
