# Generated by Django 2.2.16 on 2022-04-26 04:54

from django.db import migrations, models
import tournament.diplomacy.tasks.validate_ranking
import tournament.diplomacy.tasks.validate_year_including_start
import tournament.diplomacy.utils.game_image_location


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0063_auto_20220415_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameset',
            name='initial_image',
            field=models.ImageField(upload_to=tournament.diplomacy.utils.game_image_location.game_image_location),
        ),
        migrations.AlterField(
            model_name='preference',
            name='ranking',
            field=models.PositiveSmallIntegerField(validators=[tournament.diplomacy.tasks.validate_ranking.validate_ranking]),
        ),
        migrations.AlterField(
            model_name='supplycentreownership',
            name='year',
            field=models.PositiveSmallIntegerField(validators=[tournament.diplomacy.tasks.validate_year_including_start.validate_year_including_start]),
        ),
    ]
