# Generated by Django 2.2 on 2022-09-17 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0064_auto_20220425_2154'),
        ('tournament', '0064_auto_20220724_0951'),
    ]

    operations = [
    ]
