# Generated by Django 2.2 on 2022-10-01 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0066_auto_20221001_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='delay_game_url_publication',
            field=models.BooleanField(default=False, help_text='Check to keep game notes secret until after the tournament completes', verbose_name='Delay publishing game notes'),
        ),
    ]
