# Generated by Django 2.2 on 2022-10-01 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0068_auto_20221001_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='external_url',
            field=models.URLField(blank=True, help_text='Will be included in board call emails and game page', verbose_name='Backstabbr URL'),
        ),
    ]
