# Generated by Django 2.2 on 2022-10-02 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0069_auto_20221001_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='notes',
            field=models.CharField(blank=True, help_text='Will be included in board call emails and game page', max_length=120),
        ),
    ]
