# Generated by Django 2.2 on 2022-10-15 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0071_series'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='series',
            options={'ordering': ['name'], 'verbose_name_plural': 'Series'},
        ),
    ]
