# Generated by Django 2.1.7 on 2021-05-28 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0072_auto_20221014_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawproposal',
            name='drawing_powers',
            field=models.ManyToManyField(related_name='_drawproposal_drawing_powers_+', to='tournament.GreatPower'),
        ),
    ]
