# Generated by Django 2.1.7 on 2021-05-28 19:51

from django.db import migrations


def forward(apps, schema_editor):
    DrawProposal = apps.get_model("tournament", "DrawProposal")
    for dp in DrawProposal.objects.all():
         if dp.power_1 is not None:
             dp.drawing_powers.add(dp.power_1)
         if dp.power_2 is not None:
             dp.drawing_powers.add(dp.power_2)
         if dp.power_3 is not None:
             dp.drawing_powers.add(dp.power_3)
         if dp.power_4 is not None:
             dp.drawing_powers.add(dp.power_4)
         if dp.power_5 is not None:
             dp.drawing_powers.add(dp.power_5)
         if dp.power_6 is not None:
             dp.drawing_powers.add(dp.power_6)
         if dp.power_7 is not None:
             dp.drawing_powers.add(dp.power_7)


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0073_drawproposal_drawing_powers'),
    ]

    operations = [
        migrations.RunPython(forward)
    ]
