# Generated by Django 5.2.15 on 2026-08-06 19:23

import django.db.models.deletion
import django_countries.fields
import tournament.diplomacy.tasks.validate_sc_count
import tournament.models
import tournament.players.wdd_player
import tournament.wdd
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("tournament", "0075_auto_20210528_1300"),
        ("tournament", "0076_auto_20221014_1806"),
        ("tournament", "0077_auto_20221124_1714"),
        ("tournament", "0078_alter_drawproposal_passed"),
        ("tournament", "0079_auto_20230105_1649"),
        ("tournament", "0080_auto_20230106_1927"),
        ("tournament", "0081_alter_tournament_power_assignment"),
        ("tournament", "0082_alter_tournament_managers"),
        ("tournament", "0083_auto_20230113_1847"),
        ("tournament", "0084_dbncoverage"),
        ("tournament", "0085_playertournamentranking_wpe_score"),
        ("tournament", "0086_alter_tournament_tournament_scoring_system"),
        ("tournament", "0087_alter_round_scoring_system"),
        ("tournament", "0088_auto_20230215_2151"),
        ("tournament", "0089_playertournamentranking_unique_player_tournament_year"),
        ("tournament", "0090_gameplayer_unique_player_game"),
        ("tournament", "0091_auto_20230217_1405"),
        ("tournament", "0092_auto_20230220_2135"),
        ("tournament", "0093_auto_20230220_2142"),
        ("tournament", "0094_alter_game_external_url"),
        ("tournament", "0095_auto_20230514_1412"),
        ("tournament", "0096_alter_tournament_awards"),
        ("tournament", "0097_tournament_discord_url"),
        ("tournament", "0098_alter_round_scoring_system"),
        ("tournament", "0099_alter_tournamentplayer_awards"),
        ("tournament", "0100_player_nationalities"),
        ("tournament", "0101_auto_20231014_1312"),
        ("tournament", "0102_roundplayer_sandboxer"),
        ("tournament", "0103_alter_player_nationalities"),
        ("tournament", "0104_auto_20240222_1024"),
        ("tournament", "0105_alter_tournament_tournament_scoring_system"),
        ("tournament", "0106_alter_award_options"),
        ("tournament", "0107_alter_tournament_name"),
        ("tournament", "0108_auto_20240310_1328"),
        ("tournament", "0109_alter_player_wdd_player_id"),
        ("tournament", "0110_auto_20240615_2308"),
        ("tournament", "0111_alter_round_scoring_system"),
        ("tournament", "0112_alter_tournament_tournament_scoring_system"),
        ("tournament", "0113_alter_round_scoring_system"),
        ("tournament", "0114_alter_drawproposal_drawing_powers"),
        ("tournament", "0115_alter_dbncoverage_description"),
        ("tournament", "0116_alter_tournament_tournament_scoring_system"),
        ("tournament", "0117_alter_tournament_round_scoring_system"),
        ("tournament", "0118_round_round_end_times_valid"),
        ("tournament", "0119_tournament_tournament_starts_before_end"),
        ("tournament", "0120_tournament_handicaps_tournamentplayer_handicap"),
        ("tournament", "0121_alter_round_scoring_system"),
        ("tournament", "0122_tournamentplayer_paid"),
        ("tournament", "0123_seederbias_players_must_differ"),
        ("tournament", "0124_gameimage_phase_season_combo_valid"),
        ("tournament", "0125_alter_series_description_and_more"),
    ]

    dependencies = [
        ("tournament", "0074_auto_20210528_1251"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="drawproposal",
            name="power_1",
        ),
        migrations.RemoveField(
            model_name="drawproposal",
            name="power_2",
        ),
        migrations.RemoveField(
            model_name="drawproposal",
            name="power_3",
        ),
        migrations.RemoveField(
            model_name="drawproposal",
            name="power_4",
        ),
        migrations.RemoveField(
            model_name="drawproposal",
            name="power_5",
        ),
        migrations.RemoveField(
            model_name="drawproposal",
            name="power_6",
        ),
        migrations.RemoveField(
            model_name="drawproposal",
            name="power_7",
        ),
        migrations.AddConstraint(
            model_name="drawproposal",
            constraint=models.UniqueConstraint(
                condition=models.Q(("passed", True)),
                fields=("game",),
                name="only one passed",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="external_url",
            field=models.URLField(
                blank=True,
                help_text="Will be included in board call emails and game page",
                verbose_name="Backstabbr/WebDiplomacy URL",
            ),
        ),
        migrations.AlterField(
            model_name="drawproposal",
            name="passed",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="round",
            name="scoring_system",
            field=models.CharField(
                choices=[
                    ("7Eleven", "7Eleven"),
                    ("Bangkok", "Bangkok"),
                    ("CDiplo 100", "CDiplo 100"),
                    ("CDiplo 80", "CDiplo 80"),
                    ("Carnage with dead equal", "Carnage with dead equal"),
                    (
                        "Carnage with elimination order",
                        "Carnage with elimination order",
                    ),
                    ("Center-count Carnage", "Center-count Carnage"),
                    ("Detour09", "Detour09"),
                    ("Draw size", "Draw size"),
                    ("ManorCon", "ManorCon"),
                    ("ManorCon v2", "ManorCon v2"),
                    ("Maxonian", "Maxonian"),
                    ("OMG", "OMG"),
                    ("OpenTribute", "OpenTribute"),
                    ("Original ManorCon", "Original ManorCon"),
                    ("Solo or bust", "Solo or bust"),
                    ("Sum of Squares", "Sum of Squares"),
                    ("Tribute", "Tribute"),
                    ("Whipping", "Whipping"),
                    ("World Classic", "World Classic"),
                ],
                help_text="How to calculate a score for one game",
                max_length=40,
                validators=[tournament.models.validate_game_scoring_system],
                verbose_name="Game scoring system",
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="round_scoring_system",
            field=models.CharField(
                choices=[
                    ("Add all game scores", "Add all game scores"),
                    ("Best game counts", "Best game counts"),
                    (
                        "Best game counts. Sitters get 4005",
                        "Best game counts. Sitters get 4005",
                    ),
                    (
                        "Best game counts. Sitters get 4005 once",
                        "Best game counts. Sitters get 4005 once",
                    ),
                ],
                help_text="How to combine game scores into a round score",
                max_length=40,
                validators=[tournament.models.validate_round_scoring_system],
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="tournament_scoring_system",
            field=models.CharField(
                choices=[
                    ("Sum best 2 rounds", "Sum best 2 rounds"),
                    ("Sum best 3 rounds", "Sum best 3 rounds"),
                    (
                        "Sum best 4 games in any rounds",
                        "Sum best 4 games in any rounds",
                    ),
                    ("Sum best 4 rounds", "Sum best 4 rounds"),
                ],
                help_text="How to combine round scores into a tournament score",
                max_length=40,
                validators=[tournament.models.validate_tournament_scoring_system],
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="power_assignment",
            field=models.CharField(
                choices=[
                    ("A", "Minimising playing the same power"),
                    ("M", "Manually by TD or at the board"),
                    ("P", "Using player preferences and ranking"),
                ],
                default="A",
                max_length=1,
                verbose_name="How powers are assigned",
            ),
        ),
        migrations.DeleteModel(
            name="PowerBid",
        ),
        migrations.AlterField(
            model_name="tournament",
            name="managers",
            field=models.ManyToManyField(
                help_text="Which users can modify the tournament,<br> and see it while it is unpublished.<br>",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="gameplayer",
            name="score_dropped",
            field=models.BooleanField(
                default=False,
                help_text="Set if this score does not contribute towards the round score",
            ),
        ),
        migrations.AddField(
            model_name="roundplayer",
            name="score_dropped",
            field=models.BooleanField(
                default=False,
                help_text="Set if this score does not contribute towards the tournament score",
            ),
        ),
        migrations.CreateModel(
            name="DBNCoverage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dbn_url", models.URLField(verbose_name="DBN URL on YouTube")),
                ("description", models.CharField(max_length=30)),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tournament.tournament",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="playertournamentranking",
            name="wpe_score",
            field=models.FloatField(
                blank=True, help_text="World Performance Evaluation score", null=True
            ),
        ),
        migrations.AlterUniqueTogether(
            name="centrecount",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="gameimage",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="gameplayer",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="playeraward",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="playergameresult",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="playerranking",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="preference",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="round",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="roundplayer",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="seederbias",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="setpower",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="supplycentreownership",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="tournament",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="tournamentplayer",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="centrecount",
            constraint=models.UniqueConstraint(
                fields=("power", "game", "year"), name="unique_power_game_year"
            ),
        ),
        migrations.AddConstraint(
            model_name="gameimage",
            constraint=models.UniqueConstraint(
                fields=("game", "year", "season", "phase"),
                name="unique_game_year_season_phase",
            ),
        ),
        migrations.AddConstraint(
            model_name="gameplayer",
            constraint=models.UniqueConstraint(
                fields=("power", "game"), name="unique_power_game"
            ),
        ),
        migrations.AddConstraint(
            model_name="playeraward",
            constraint=models.UniqueConstraint(
                fields=("player", "tournament", "date", "name"),
                name="unique_player_tournament_date_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="playergameresult",
            constraint=models.UniqueConstraint(
                fields=("tournament_name", "game_name", "player", "power"),
                name="unique_names_player_power",
            ),
        ),
        migrations.AddConstraint(
            model_name="playerranking",
            constraint=models.UniqueConstraint(
                fields=("player", "system"), name="unique_player_system"
            ),
        ),
        migrations.AddConstraint(
            model_name="preference",
            constraint=models.UniqueConstraint(
                fields=("player", "power"), name="unique_player_power"
            ),
        ),
        migrations.AddConstraint(
            model_name="preference",
            constraint=models.UniqueConstraint(
                fields=("player", "ranking"), name="unique_player_ranking"
            ),
        ),
        migrations.AddConstraint(
            model_name="round",
            constraint=models.UniqueConstraint(
                fields=("tournament", "start"), name="unique_tournament_start"
            ),
        ),
        migrations.AddConstraint(
            model_name="roundplayer",
            constraint=models.UniqueConstraint(
                fields=("player", "the_round"), name="unique_player_round"
            ),
        ),
        migrations.AddConstraint(
            model_name="seederbias",
            constraint=models.UniqueConstraint(
                fields=("player1", "player2"), name="unique_player_pair"
            ),
        ),
        migrations.AddConstraint(
            model_name="setpower",
            constraint=models.UniqueConstraint(
                fields=("the_set", "power"), name="unique_set_power"
            ),
        ),
        migrations.AddConstraint(
            model_name="supplycentreownership",
            constraint=models.UniqueConstraint(
                fields=("sc", "game", "year"), name="unique_sc_game_year"
            ),
        ),
        migrations.AddConstraint(
            model_name="tournament",
            constraint=models.UniqueConstraint(
                fields=("name", "start_date"), name="unique_name_date"
            ),
        ),
        migrations.AddConstraint(
            model_name="tournamentplayer",
            constraint=models.UniqueConstraint(
                fields=("player", "tournament"), name="unique_player_tournament"
            ),
        ),
        migrations.AddConstraint(
            model_name="playertournamentranking",
            constraint=models.UniqueConstraint(
                fields=("player", "tournament", "year"),
                name="unique_player_tournament_year",
            ),
        ),
        migrations.AddConstraint(
            model_name="gameplayer",
            constraint=models.UniqueConstraint(
                fields=("player", "game"), name="unique_player_game"
            ),
        ),
        migrations.AddConstraint(
            model_name="drawproposal",
            constraint=models.CheckConstraint(
                condition=models.Q(("season__in", ["S", "F"])),
                name="drawproposal_season_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="gameimage",
            constraint=models.CheckConstraint(
                condition=models.Q(("season__in", ["S", "F"])),
                name="gameimage_season_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="gameimage",
            constraint=models.CheckConstraint(
                condition=models.Q(("phase__in", ["M", "R", "X"])),
                name="gameimage_phase_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="playergameresult",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("result__in", ["W", "D2", "D3", "D4", "D5", "D6", "D7", "L"]),
                    ("result", ""),
                    _connector="OR",
                ),
                name="playergameresult_result_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="tournament",
            constraint=models.CheckConstraint(
                condition=models.Q(("draw_secrecy__in", ["S", "C"])),
                name="tournament_draw_secrecy_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="tournament",
            constraint=models.CheckConstraint(
                condition=models.Q(("power_assignment__in", ["A", "M", "P"])),
                name="tournament_power_assignment_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="tournament",
            constraint=models.CheckConstraint(
                condition=models.Q(("best_country_criterion__in", ["S", "D"])),
                name="tournament_best_country_criterion_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="tournament",
            constraint=models.CheckConstraint(
                condition=models.Q(("format__in", ["F", "V"])),
                name="tournament_format_valid",
            ),
        ),
        migrations.AlterModelOptions(
            name="dbncoverage",
            options={"verbose_name_plural": "DBN coverages"},
        ),
        migrations.AlterField(
            model_name="playergameresult",
            name="final_sc_count",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    tournament.diplomacy.tasks.validate_sc_count.validate_sc_count
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="centrecount",
            constraint=models.CheckConstraint(
                condition=models.Q(("year__gte", 1900)), name="centrecount_year_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="centrecount",
            constraint=models.CheckConstraint(
                condition=models.Q(("count__lte", 34)), name="centrecount_count_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="drawproposal",
            constraint=models.CheckConstraint(
                condition=models.Q(("year__gte", 1901)), name="drawproposal_year_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="gameimage",
            constraint=models.CheckConstraint(
                condition=models.Q(("year__gte", 1901)), name="gameimage_year_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="playeraward",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("final_sc_count__lte", 34),
                    ("final_sc_count__isnull", True),
                    _connector="OR",
                ),
                name="playeraward_final_sc_count_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="playergameresult",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("final_sc_count__lte", 34),
                    ("final_sc_count__isnull", True),
                    _connector="OR",
                ),
                name="playergameresult_final_sc_count_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="playergameresult",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("year_eliminated__gte", 1901),
                    ("year_eliminated__isnull", True),
                    _connector="OR",
                ),
                name="playergameresult_year_eliminated_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="round",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("final_year__gte", 1901),
                    ("final_year__isnull", True),
                    _connector="OR",
                ),
                name="round_final_year_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="supplycentreownership",
            constraint=models.CheckConstraint(
                condition=models.Q(("year__gte", 1900)),
                name="supplycentreownership_year_valid",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="external_url",
            field=models.URLField(
                blank=True,
                help_text="Will be included in board call emails and game page",
                verbose_name="Backstabbr URL",
            ),
        ),
        migrations.CreateModel(
            name="Award",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40, unique=True)),
                ("description", models.CharField(max_length=200)),
                (
                    "power",
                    models.ForeignKey(
                        blank=True,
                        help_text='Set if this award is associated with a specific power (e.g. "Best Italy")',
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tournament.greatpower",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="tournament",
            name="awards",
            field=models.ManyToManyField(
                help_text="Which achievements may be recognised.", to="tournament.award"
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="discord_url",
            field=models.URLField(
                blank=True,
                help_text="Board calls will be posted here",
                null=True,
                verbose_name="Discord webhook URL",
            ),
        ),
        migrations.AddField(
            model_name="tournamentplayer",
            name="awards",
            field=models.ManyToManyField(blank=True, to="tournament.award"),
        ),
        migrations.AddField(
            model_name="playeraward",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="playergameresult",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="playerranking",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="playertournamentranking",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="roundplayer",
            name="sandboxer",
            field=models.BooleanField(
                default=False,
                help_text="set if the player is willing to record a game this round",
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="nationalities",
            field=django_countries.fields.CountryField(
                blank=True, max_length=767, multiple=True
            ),
        ),
        migrations.RemoveField(
            model_name="player",
            name="_wdd_name",
        ),
        migrations.AlterField(
            model_name="tournament",
            name="name",
            field=models.CharField(
                help_text="Year will be appended based on start date", max_length=60
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="_wdd_firstname",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="player",
            name="_wdd_lastname",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name="player",
            name="first_name",
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name="player",
            name="last_name",
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name="player",
            name="wdd_player_id",
            field=tournament.players.wdd_player.WDDPlayerIdField(
                blank=True,
                null=True,
                unique=True,
                validators=[tournament.wdd.validate_wdd_player_id],
                verbose_name="WDD player id",
            ),
        ),
        migrations.AlterField(
            model_name="drawproposal",
            name="passed",
            field=tournament.models.DPPassedField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="series",
            name="slug",
            field=tournament.models.NameSlugField(unique=True),
        ),
        migrations.AlterField(
            model_name="tournamentplayer",
            name="backstabbr_username",
            field=tournament.models.TPPlayerField(
                blank=True,
                help_text="Username on the backstabbr website",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="tournamentplayer",
            name="location",
            field=tournament.models.TPPlayerField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name="tournamentplayer",
            name="unranked",
            field=tournament.models.TPUnrankedField(
                default=False,
                help_text="Set this to ignore this player when determining rankings",
                verbose_name="Ineligible for awards",
            ),
        ),
        migrations.AlterField(
            model_name="round",
            name="scoring_system",
            field=models.CharField(
                choices=[
                    ("7Eleven", "7Eleven"),
                    ("Bangkok", "Bangkok"),
                    ("C-Diplo Namur", "C-Diplo Namur"),
                    ("CDiplo 100", "CDiplo 100"),
                    ("CDiplo 80", "CDiplo 80"),
                    ("Carnage 2023", "Carnage 2023"),
                    ("Carnage with dead equal", "Carnage with dead equal"),
                    (
                        "Carnage with elimination order",
                        "Carnage with elimination order",
                    ),
                    ("Center-count Carnage", "Center-count Carnage"),
                    ("Detour09", "Detour09"),
                    ("Draw size", "Draw size"),
                    ("ManorCon", "ManorCon"),
                    ("ManorCon v2", "ManorCon v2"),
                    ("Maxonian", "Maxonian"),
                    ("OMG", "OMG"),
                    ("OpenTribute", "OpenTribute"),
                    ("Original ManorCon", "Original ManorCon"),
                    ("Solo or bust", "Solo or bust"),
                    ("Sum of Squares", "Sum of Squares"),
                    ("Summer Classic", "Summer Classic"),
                    ("Tribute", "Tribute"),
                    ("Whipping", "Whipping"),
                    ("World Classic", "World Classic"),
                ],
                help_text="How to calculate a score for one game",
                max_length=40,
                validators=[tournament.models.validate_game_scoring_system],
                verbose_name="Game scoring system",
            ),
        ),
        migrations.AlterField(
            model_name="drawproposal",
            name="drawing_powers",
            field=models.ManyToManyField(related_name="+", to="tournament.greatpower"),
        ),
        migrations.AlterField(
            model_name="dbncoverage",
            name="description",
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="tournament_scoring_system",
            field=models.CharField(
                choices=[
                    ("Best single game result", "Best single game result"),
                    (
                        "Sum best 2 games plus half the average of the rest",
                        "Sum best 2 games plus half the average of the rest",
                    ),
                    ("Sum best 2 rounds", "Sum best 2 rounds"),
                    (
                        "Sum best 3 games in any rounds",
                        "Sum best 3 games in any rounds",
                    ),
                    ("Sum best 3 rounds", "Sum best 3 rounds"),
                    (
                        "Sum best 4 games in any rounds",
                        "Sum best 4 games in any rounds",
                    ),
                    ("Sum best 4 rounds", "Sum best 4 rounds"),
                ],
                help_text="How to combine round scores into a tournament score",
                max_length=50,
                validators=[tournament.models.validate_tournament_scoring_system],
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="round_scoring_system",
            field=models.CharField(
                choices=[
                    ("None", "None"),
                    ("Add all game scores", "Add all game scores"),
                    ("Best game counts", "Best game counts"),
                    (
                        "Best game counts. Sitters get 4005",
                        "Best game counts. Sitters get 4005",
                    ),
                    (
                        "Best game counts. Sitters get 4005 once",
                        "Best game counts. Sitters get 4005 once",
                    ),
                ],
                help_text="How to combine game scores into a round score",
                max_length=40,
                validators=[tournament.models.validate_round_scoring_system],
            ),
        ),
        migrations.AddConstraint(
            model_name="round",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("earliest_end_time__isnull", True),
                        ("latest_end_time__isnull", True),
                    ),
                    ("latest_end_time__gte", models.F("earliest_end_time")),
                    _connector="OR",
                ),
                name="round_end_times_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="tournament",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_date__gte", models.F("start_date"))),
                name="tournament_starts_before_end",
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="handicaps",
            field=models.BooleanField(
                default=False,
                help_text="Check to give each TournamentPlayer a predetermined score bonus",
            ),
        ),
        migrations.AddField(
            model_name="tournamentplayer",
            name="handicap",
            field=models.FloatField(
                default=0.0,
                help_text="Secret bonus score added after all games end. Only used if enabled for the Tournament",
            ),
        ),
        migrations.AlterField(
            model_name="round",
            name="scoring_system",
            field=models.CharField(
                choices=[
                    ("7Eleven", "7Eleven"),
                    ("Bangkok", "Bangkok"),
                    ("C-Diplo Namur", "C-Diplo Namur"),
                    ("CDiplo 100", "CDiplo 100"),
                    ("CDiplo 80", "CDiplo 80"),
                    ("Carnage 2023", "Carnage 2023"),
                    ("Carnage with dead equal", "Carnage with dead equal"),
                    (
                        "Carnage with elimination order",
                        "Carnage with elimination order",
                    ),
                    ("Center-count Carnage", "Center-count Carnage"),
                    ("Detour09", "Detour09"),
                    ("Draw size", "Draw size"),
                    ("Haight v1.0", "Haight v1.0"),
                    ("ManorCon", "ManorCon"),
                    ("ManorCon v2", "ManorCon v2"),
                    ("Maxonian", "Maxonian"),
                    ("OMG", "OMG"),
                    ("OpenTribute", "OpenTribute"),
                    ("Original ManorCon", "Original ManorCon"),
                    ("Solo or bust", "Solo or bust"),
                    ("Sum of Squares", "Sum of Squares"),
                    ("Summer Classic", "Summer Classic"),
                    ("Tribute", "Tribute"),
                    ("Whipping", "Whipping"),
                    ("World Classic", "World Classic"),
                ],
                help_text="How to calculate a score for one game",
                max_length=40,
                validators=[tournament.models.validate_game_scoring_system],
                verbose_name="Game scoring system",
            ),
        ),
        migrations.AddField(
            model_name="tournamentplayer",
            name="paid",
            field=models.BooleanField(
                default=False, help_text="Have they paid any registration fee?"
            ),
        ),
        migrations.AddConstraint(
            model_name="seederbias",
            constraint=models.CheckConstraint(
                condition=models.Q(("player1", models.F("player2")), _negated=True),
                name="players_must_differ",
            ),
        ),
        migrations.AddConstraint(
            model_name="gameimage",
            constraint=models.CheckConstraint(
                condition=models.Q(("season", "S"), ("phase", "X"), _negated=True),
                name="phase_season_combo_valid",
            ),
        ),
        migrations.AlterField(
            model_name="series",
            name="description",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="tournament",
            name="discord_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Board calls will be posted here",
                verbose_name="Discord webhook URL",
            ),
            preserve_default=False,
        ),
    ]
