# Generated by Django 2.1.7 on 2021-05-28 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0074_auto_20210528_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drawproposal',
            name='power_1',
        ),
        migrations.RemoveField(
            model_name='drawproposal',
            name='power_2',
        ),
        migrations.RemoveField(
            model_name='drawproposal',
            name='power_3',
        ),
        migrations.RemoveField(
            model_name='drawproposal',
            name='power_4',
        ),
        migrations.RemoveField(
            model_name='drawproposal',
            name='power_5',
        ),
        migrations.RemoveField(
            model_name='drawproposal',
            name='power_6',
        ),
        migrations.RemoveField(
            model_name='drawproposal',
            name='power_7',
        ),
    ]
