# Generated by Django 2.2 on 2022-10-15 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0075_auto_20210528_1300'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='drawproposal',
            constraint=models.UniqueConstraint(condition=models.Q(passed=True), fields=('game',), name='only one passed'),
        ),
    ]
