# Generated by Django 2.2 on 2022-11-25 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0076_auto_20221014_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='external_url',
            field=models.URLField(blank=True, help_text='Will be included in board call emails and game page', verbose_name='Backstabbr/WebDiplomacy URL'),
        ),
    ]
