# Generated by Django 3.2.16 on 2023-01-06 00:49

from django.db import migrations, models
import tournament.models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0078_alter_drawproposal_passed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='scoring_system',
            field=models.CharField(choices=[('Bangkok', 'Bangkok'), ('CDiplo 100', 'CDiplo 100'), ('CDiplo 80', 'CDiplo 80'), ('Carnage with dead equal', 'Carnage with dead equal'), ('Carnage with elimination order', 'Carnage with elimination order'), ('Center-count Carnage', 'Center-count Carnage'), ('Detour09', 'Detour09'), ('Draw size', 'Draw size'), ('ManorCon', 'ManorCon'), ('ManorCon v2', 'ManorCon v2'), ('Maxonian', 'Maxonian'), ('OMG', 'OMG'), ('OpenTribute', 'OpenTribute'), ('Original ManorCon', 'Original ManorCon'), ('Solo or bust', 'Solo or bust'), ('Sum of Squares', 'Sum of Squares'), ('Tribute', 'Tribute'), ('Whipping', 'Whipping'), ('World Classic', 'World Classic')], help_text='How to calculate a score for one game', max_length=40, validators=[tournament.models.validate_game_scoring_system], verbose_name='Game scoring system'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='round_scoring_system',
            field=models.CharField(choices=[('Add all game scores', 'Add all game scores'), ('Best game counts', 'Best game counts'), ('Best game counts. Sitters get 4005', 'Best game counts. Sitters get 4005'), ('Best game counts. Sitters get 4005 once', 'Best game counts. Sitters get 4005 once')], help_text='How to combine game scores into a round score', max_length=40, validators=[tournament.models.validate_round_scoring_system]),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_scoring_system',
            field=models.CharField(choices=[('Sum best 2 rounds', 'Sum best 2 rounds'), ('Sum best 3 rounds', 'Sum best 3 rounds'), ('Sum best 4 rounds', 'Sum best 4 rounds')], help_text='How to combine round scores into a tournament score', max_length=40, validators=[tournament.models.validate_tournament_scoring_system]),
        ),
    ]
