# Generated by Django 3.2.16 on 2023-01-07 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0079_auto_20230105_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='power_assignment',
            field=models.CharField(choices=[('A', 'Minimising playing the same power'), ('M', 'Manually by TD or at the board'), ('P', 'Using player preferences and ranking')], default='M', max_length=1, verbose_name='How powers are assigned'),
        ),
        migrations.DeleteModel(
            name='PowerBid',
        ),
    ]
