# Generated by Django 3.2.16 on 2023-01-10 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0080_auto_20230106_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='power_assignment',
            field=models.CharField(choices=[('A', 'Minimising playing the same power'), ('M', 'Manually by TD or at the board'), ('P', 'Using player preferences and ranking')], default='A', max_length=1, verbose_name='How powers are assigned'),
        ),
    ]
