# Generated by Django 3.2.16 on 2023-01-14 02:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournament', '0081_alter_tournament_power_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='managers',
            field=models.ManyToManyField(help_text='Which users can modify the tournament,<br> and see it while it is unpublished.<br>', to=settings.AUTH_USER_MODEL),
        ),
    ]
