# Generated by Django 3.2.16 on 2023-02-09 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0083_auto_20230113_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBNCoverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbn_url', models.URLField(verbose_name='DBN URL on YouTube')),
                ('description', models.CharField(max_length=30)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.tournament')),
            ],
        ),
    ]
