# Generated by Django 3.2.17 on 2023-02-10 06:14

from django.db import migrations, models
import tournament.models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0085_playertournamentranking_wpe_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='tournament_scoring_system',
            field=models.CharField(choices=[('Sum best 2 rounds', 'Sum best 2 rounds'), ('Sum best 3 rounds', 'Sum best 3 rounds'), ('Sum best 4 games in any rounds', 'Sum best 4 games in any rounds'), ('Sum best 4 rounds', 'Sum best 4 rounds')], help_text='How to combine round scores into a tournament score', max_length=40, validators=[tournament.models.validate_tournament_scoring_system]),
        ),
    ]
