# Generated by Django 3.2.17 on 2023-02-16 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0087_alter_round_scoring_system'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='centrecount',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='gameimage',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='gameplayer',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='playeraward',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='playergameresult',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='playerranking',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='preference',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='round',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='roundplayer',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='seederbias',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='setpower',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='supplycentreownership',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='tournament',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='tournamentplayer',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='centrecount',
            constraint=models.UniqueConstraint(fields=('power', 'game', 'year'), name='unique_power_game_year'),
        ),
        migrations.AddConstraint(
            model_name='gameimage',
            constraint=models.UniqueConstraint(fields=('game', 'year', 'season', 'phase'), name='unique_game_year_season_phase'),
        ),
        migrations.AddConstraint(
            model_name='gameplayer',
            constraint=models.UniqueConstraint(fields=('power', 'game'), name='unique_power_game'),
        ),
        migrations.AddConstraint(
            model_name='playeraward',
            constraint=models.UniqueConstraint(fields=('player', 'tournament', 'date', 'name'), name='unique_player_tournament_date_name'),
        ),
        migrations.AddConstraint(
            model_name='playergameresult',
            constraint=models.UniqueConstraint(fields=('tournament_name', 'game_name', 'player', 'power'), name='unique_names_player_power'),
        ),
        migrations.AddConstraint(
            model_name='playerranking',
            constraint=models.UniqueConstraint(fields=('player', 'system'), name='unique_player_system'),
        ),
        migrations.AddConstraint(
            model_name='preference',
            constraint=models.UniqueConstraint(fields=('player', 'power'), name='unique_player_power'),
        ),
        migrations.AddConstraint(
            model_name='preference',
            constraint=models.UniqueConstraint(fields=('player', 'ranking'), name='unique_player_ranking'),
        ),
        migrations.AddConstraint(
            model_name='round',
            constraint=models.UniqueConstraint(fields=('tournament', 'start'), name='unique_tournament_start'),
        ),
        migrations.AddConstraint(
            model_name='roundplayer',
            constraint=models.UniqueConstraint(fields=('player', 'the_round'), name='unique_player_round'),
        ),
        migrations.AddConstraint(
            model_name='seederbias',
            constraint=models.UniqueConstraint(fields=('player1', 'player2'), name='unique_player_pair'),
        ),
        migrations.AddConstraint(
            model_name='setpower',
            constraint=models.UniqueConstraint(fields=('the_set', 'power'), name='unique_set_power'),
        ),
        migrations.AddConstraint(
            model_name='supplycentreownership',
            constraint=models.UniqueConstraint(fields=('sc', 'game', 'year'), name='unique_sc_game_year'),
        ),
        migrations.AddConstraint(
            model_name='tournament',
            constraint=models.UniqueConstraint(fields=('name', 'start_date'), name='unique_name_date'),
        ),
        migrations.AddConstraint(
            model_name='tournamentplayer',
            constraint=models.UniqueConstraint(fields=('player', 'tournament'), name='unique_player_tournament'),
        ),
    ]
