# Generated by Django 3.2.17 on 2023-02-16 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0088_auto_20230215_2151'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='playertournamentranking',
            constraint=models.UniqueConstraint(fields=('player', 'tournament', 'year'), name='unique_player_tournament_year'),
        ),
    ]
