# Generated by Django 3.2.17 on 2023-02-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0089_playertournamentranking_unique_player_tournament_year'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='gameplayer',
            constraint=models.UniqueConstraint(fields=('player', 'game'), name='unique_player_game'),
        ),
    ]
