# Generated by Django 3.2.18 on 2023-05-14 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0093_auto_20230220_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='external_url',
            field=models.URLField(blank=True, help_text='Will be included in board call emails and game page', verbose_name='Backstabbr URL'),
        ),
    ]
