# Generated by Django 3.2.18 on 2023-05-14 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0094_alter_game_external_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('power', models.ForeignKey(blank=True, help_text='Set if this award is associated with a specific power (e.g. "Best Italy")', null=True, on_delete=django.db.models.deletion.CASCADE, to='tournament.greatpower')),
            ],
        ),
        migrations.AddField(
            model_name='tournament',
            name='awards',
            field=models.ManyToManyField(to='tournament.Award'),
        ),
        migrations.AddField(
            model_name='tournamentplayer',
            name='awards',
            field=models.ManyToManyField(to='tournament.Award'),
        ),
    ]
