# Generated by Django 3.2.19 on 2023-06-05 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0095_auto_20230514_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='awards',
            field=models.ManyToManyField(help_text='Which achievements may be recognised.', to='tournament.Award'),
        ),
    ]
