# Generated by Django 3.2.18 on 2023-06-05 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0096_alter_tournament_awards'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='discord_url',
            field=models.URLField(blank=True, help_text='Board calls will be posted here', null=True, verbose_name='Discord webhook URL'),
        ),
    ]
