# Generated by Django 3.2.20 on 2023-10-12 19:25

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0099_alter_tournamentplayer_awards'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='nationalities',
            field=django_countries.fields.CountryField(blank=True, max_length=746, multiple=True),
        ),
    ]
