# Generated by Django 3.2.18 on 2023-10-14 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0100_player_nationalities'),
    ]

    operations = [
        migrations.AddField(
            model_name='playeraward',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='playergameresult',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='playerranking',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='playertournamentranking',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
