# Generated by Django 3.2.23 on 2023-11-30 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0101_auto_20231014_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundplayer',
            name='sandboxer',
            field=models.BooleanField(default=False, help_text='set if the player is willing to record a game this round'),
        ),
    ]
