# Generated by Django 3.2.23 on 2024-01-09 06:21

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0102_roundplayer_sandboxer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='nationalities',
            field=django_countries.fields.CountryField(blank=True, max_length=767, multiple=True),
        ),
    ]
