# Generated by Django 3.2.24 on 2024-02-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0103_alter_player_nationalities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='_wdd_name',
        ),
        migrations.AddField(
            model_name='player',
            name='_wdd_firstname',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='player',
            name='_wdd_lastname',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
