# Generated by Django 3.2.24 on 2024-03-10 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0105_alter_tournament_tournament_scoring_system'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='award',
            options={'ordering': ['name']},
        ),
    ]
