# Generated by Django 3.2.24 on 2024-03-10 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0106_alter_award_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(help_text='Year will be appended based on start date', max_length=60),
        ),
    ]
