# Generated by Django 3.2.24 on 2024-03-10 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0107_alter_tournament_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='_wdd_firstname',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='player',
            name='_wdd_lastname',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='player',
            name='first_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_name',
            field=models.CharField(max_length=40),
        ),
    ]
