# Generated by Django 3.2.24 on 2024-06-16 06:08

from django.db import migrations
import tournament.models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0109_alter_player_wdd_player_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawproposal',
            name='passed',
            field=tournament.models.DPPassedField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='slug',
            field=tournament.models.SeriesSlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='tournamentplayer',
            name='backstabbr_username',
            field=tournament.models.TPPlayerField(blank=True, help_text='Username on the backstabbr website', max_length=40),
        ),
        migrations.AlterField(
            model_name='tournamentplayer',
            name='location',
            field=tournament.models.TPPlayerField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='tournamentplayer',
            name='unranked',
            field=tournament.models.TPUnrankedField(default=False, help_text='Set this to ignore this player when determining rankings', verbose_name='Ineligible for awards'),
        ),
    ]
