# Generated by Django 3.2.25 on 2024-06-19 06:56

from django.db import migrations, models
import tournament.models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0111_alter_round_scoring_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='tournament_scoring_system',
            field=models.CharField(choices=[('Best single game result', 'Best single game result'), ('Sum best 2 rounds', 'Sum best 2 rounds'), ('Sum best 3 games in any rounds', 'Sum best 3 games in any rounds'), ('Sum best 3 rounds', 'Sum best 3 rounds'), ('Sum best 4 games in any rounds', 'Sum best 4 games in any rounds'), ('Sum best 4 rounds', 'Sum best 4 rounds')], help_text='How to combine round scores into a tournament score', max_length=40, validators=[tournament.models.validate_tournament_scoring_system]),
        ),
    ]
