# Generated by Django 4.2.16 on 2024-10-02 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0113_alter_round_scoring_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawproposal',
            name='drawing_powers',
            field=models.ManyToManyField(related_name='+', to='tournament.greatpower'),
        ),
    ]
