# Generated by Django 4.2.16 on 2024-10-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0114_alter_drawproposal_drawing_powers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbncoverage',
            name='description',
            field=models.CharField(max_length=80),
        ),
    ]
