# Generated by Django 4.2.16 on 2024-10-04 21:48

from django.db import migrations, models
import tournament.models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0115_alter_dbncoverage_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='tournament_scoring_system',
            field=models.CharField(choices=[('Best single game result', 'Best single game result'), ('Sum best 2 games plus half the average of the rest', 'Sum best 2 games plus half the average of the rest'), ('Sum best 2 rounds', 'Sum best 2 rounds'), ('Sum best 3 games in any rounds', 'Sum best 3 games in any rounds'), ('Sum best 3 rounds', 'Sum best 3 rounds'), ('Sum best 4 games in any rounds', 'Sum best 4 games in any rounds'), ('Sum best 4 rounds', 'Sum best 4 rounds')], help_text='How to combine round scores into a tournament score', max_length=50, validators=[tournament.models.validate_tournament_scoring_system]),
        ),
    ]
