# Generated by Django 4.2.16 on 2024-10-12 06:07

from django.db import migrations, models
import tournament.models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0116_alter_tournament_tournament_scoring_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='round_scoring_system',
            field=models.CharField(choices=[('None', 'None'), ('Add all game scores', 'Add all game scores'), ('Best game counts', 'Best game counts'), ('Best game counts. Sitters get 4005', 'Best game counts. Sitters get 4005'), ('Best game counts. Sitters get 4005 once', 'Best game counts. Sitters get 4005 once')], help_text='How to combine game scores into a round score', max_length=40, validators=[tournament.models.validate_round_scoring_system]),
        ),
    ]
