# Generated by Django 4.2.16 on 2024-10-14 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0118_round_round_end_times_valid'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tournament',
            constraint=models.CheckConstraint(check=models.Q(('end_date__gte', models.F('start_date'))), name='tournament_starts_before_end'),
        ),
    ]
