# Generated by Django 4.2.16 on 2024-10-15 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0119_tournament_tournament_starts_before_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='handicaps',
            field=models.BooleanField(default=False, help_text='Check to give each TournamentPlayer a predetermined score bonus'),
        ),
        migrations.AddField(
            model_name='tournamentplayer',
            name='handicap',
            field=models.FloatField(default=0.0, help_text='Secret bonus score added after all games end. Only used if enabled for the Tournament'),
        ),
    ]
