# Generated by Django 4.2.16 on 2024-11-05 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0121_alter_round_scoring_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentplayer',
            name='paid',
            field=models.BooleanField(default=False, help_text='Have they paid any registration fee?'),
        ),
    ]
