# Generated by Django 4.2.16 on 2024-11-17 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0122_tournamentplayer_paid'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='seederbias',
            constraint=models.CheckConstraint(check=models.Q(('player1', models.F('player2')), _negated=True), name='players_must_differ'),
        ),
    ]
