# Generated by Django 4.2.16 on 2024-11-17 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0123_seederbias_players_must_differ'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='gameimage',
            constraint=models.CheckConstraint(check=models.Q(('season', 'S'), ('phase', 'X'), _negated=True), name='phase_season_combo_valid'),
        ),
    ]
