# Generated by Django 4.2.16 on 2024-11-13 08:03

from django.db import migrations, models


def set_is_finished(apps, schema_editor):
    Round = apps.get_model("tournament", "Round")
    for row in Round.objects.all():
        row.is_finished = row.game_set.exists() and not row.game_set.filter(is_finished=False).exists()
        row.save(update_fields=["is_finished"])


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0125_alter_series_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(set_is_finished, migrations.RunPython.noop),
    ]
