# Generated by Django 4.2.16 on 2024-11-13 08:05

from django.db import migrations, models


def set_is_finished(apps, schema_editor):
    Tournament = apps.get_model("tournament", "Tournament")
    for row in Tournament.objects.all():
        row.is_finished = row.round_set.exists() and not row.round_set.filter(is_finished=False).exists()
        row.save(update_fields=["is_finished"])


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0126_round_is_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(set_is_finished, migrations.RunPython.noop),
    ]
