# Generated by Django 4.2.16 on 2025-01-02 22:35

from django.db import migrations, models
import tournament.models


def forward(apps, schema_editor):
    """
    Switch away from round scoring systems with sitting bonus
    """
    Tournament = apps.get_model("tournament", "Tournament")
    for t in Tournament.objects.all():
        # There are only 4 RoundScoringSystems, so we can use shortcuts here
        if 'Sitters get' in t.round_scoring_system:
            t.round_scoring_system = 'Best game counts'
            t.non_player_round_score = 4005.0
            if 'once' in t.round_scoring_system:
                t.non_player_round_score_once = True
            else:
                t.non_player_round_score_once = False
            t.save(update_fields=['round_scoring_system',
                                  'non_player_round_score',
                                  'non_player_round_score_once'])


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0128_alter_round_scoring_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='non_player_round_score',
            field=models.FloatField(default=0.0, help_text='If a Player volunteers to sit out a round, what score do they get?'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='non_player_round_score_once',
            field=models.BooleanField(default=False, help_text='Can a player only get the sitting out score for one round?'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='round_scoring_system',
            field=models.CharField(choices=[('None', 'None'), ('Add all game scores', 'Add all game scores'), ('Best game counts', 'Best game counts')], help_text='How to combine game scores into a round score', max_length=40, validators=[tournament.models.validate_round_scoring_system]),
        ),
        migrations.RunPython(forward, migrations.RunPython.noop),
    ]
