# Generated by Django 4.2.16 on 2025-01-18 21:48

from django.db import migrations, models
import django.db.models.deletion


def create_playertitles(apps, schema_editor):
    """Create a PlayerTitle from appropriate PlayerTournamentRankings"""
    PlayerTournamentRanking = apps.get_model('tournament', 'PlayerTournamentRanking')
    PlayerTitle = apps.get_model('tournament', 'PlayerTitle')
    for ptr in PlayerTournamentRanking.objects.exclude(title=''):
        PlayerTitle.objects.create(player=ptr.player,
                                   title=ptr.title,
                                   year=ptr.year,
                                   ranking=ptr)
        # If the PlayerTournamentRanking doesn't have a tournament id,
        # it was created from wikipedia data
        if not ptr.wdd_tournament_id:
            ptr.delete()


def remove_playertitles(apps, schema_editor):
    """Remove all PlayerTitles"""
    PlayerTitle = apps.get_model('tournament', 'PlayerTitle')
    PlayerTitle.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0133_tournament_show_current_scores'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('year', models.PositiveSmallIntegerField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.player')),
                ('ranking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournament.playertournamentranking')),
            ],
        ),
        migrations.AddConstraint(
            model_name='playertitle',
            constraint=models.UniqueConstraint(fields=('player', 'title', 'year'), name='unique_player_title_year'),
        ),
        migrations.RunPython(create_playertitles, remove_playertitles),
    ]
