# Generated by Django 4.2.16 on 2025-01-18 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0134_playertitle_playertitle_unique_player_title_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playertournamentranking',
            name='title',
        ),
    ]
