# Generated by Django 4.2.16 on 2025-01-15 06:07

from django.db import migrations, models
import tournament.wdr


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0135_remove_playertournamentranking_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='wdr_player_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, validators=[tournament.wdr.validate_wdr_player_id], verbose_name='WDR player id'),
        ),
        migrations.AddField(
            model_name='playeraward',
            name='wdr_tournament_id',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[tournament.wdr.validate_wdr_tournament_id], verbose_name='WDR tournament id'),
        ),
        migrations.AddField(
            model_name='playergameresult',
            name='wdr_tournament_id',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[tournament.wdr.validate_wdr_tournament_id], verbose_name='WDR tournament id'),
        ),
        migrations.AddField(
            model_name='playertournamentranking',
            name='wdr_tournament_id',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[tournament.wdr.validate_wdr_tournament_id], verbose_name='WDR tournament id'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='wdr_tournament_id',
            field=models.PositiveIntegerField(blank=True, help_text='Add this after the tournament is complete and results have been uploaded to the WDR', null=True, validators=[tournament.wdr.validate_wdr_tournament_id], verbose_name="This tournament's id in the WDR"),
        ),
    ]
