# Generated by Django 4.2.16 on 2025-01-22 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0137_alter_playertitle_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playergameresult',
            name='tournament_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='playertournamentranking',
            name='tournament',
            field=models.CharField(max_length=100),
        ),
    ]
