# Generated by Django 4.2.16 on 2025-01-22 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0138_alter_playergameresult_tournament_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playeraward',
            name='tournament',
            field=models.CharField(max_length=100),
        ),
    ]
