# Generated by Django 4.2.16 on 2025-01-22 06:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0139_alter_playeraward_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='is_team_round',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='team_size',
            field=models.PositiveSmallIntegerField(blank=True, help_text='If there are teams, number of players per team', null=True, validators=[django.core.validators.MinValueValidator(2)]),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Must be unique within the tournament', max_length=20)),
                ('score', models.FloatField(default=0.0)),
                ('players', models.ManyToManyField(to='tournament.player')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.tournament')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('tournament', 'name'), name='unique_tournament_name'),
        ),
    ]
