# Generated by Django 4.2.17 on 2025-02-04 04:42

from django.db import migrations, models
import tournament.models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0139_alter_playeraward_tournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(help_text='Must be unique within the tournament. No spaces', max_length=200, validators=[tournament.models.validate_game_name]),
        ),
    ]
