# Generated by Django 4.2.20 on 2025-04-19 04:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0143_alter_game_external_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centrecount',
            name='count',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(34)]),
        ),
        migrations.AlterField(
            model_name='drawproposal',
            name='votes_in_favour',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AlterField(
            model_name='playergameresult',
            name='final_sc_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(34)]),
        ),
        migrations.AlterField(
            model_name='preference',
            name='ranking',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)]),
        ),
    ]
