# Generated by Django 4.2.20 on 2025-04-24 05:27

from django.db import migrations, models


from tournament.players import _split_wdd_game_name


def add_numbers(apps, schema_editor):
    """Add game_number and round_number attributes"""
    PlayerGameResult = apps.get_model('tournament', 'PlayerGameResult')
    for pgr in PlayerGameResult.objects.all():
        pgr.round_number, pgr.game_number = _split_wdd_game_name(pgr.game_name)
        pgr.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0147_alter_tournament_tournament_scoring_system'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='playergameresult',
            name='unique_names_player_power',
        ),
        migrations.AddField(
            model_name='playergameresult',
            name='game_number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='playergameresult',
            name='round_number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.RunPython(add_numbers, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='playergameresult',
            constraint=models.UniqueConstraint(fields=('tournament_name', 'round_number', 'game_number', 'player', 'power'), name='unique_names_player_power'),
        ),
    ]
