# Generated by Django 4.2.20 on 2025-04-24 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0148_remove_playergameresult_unique_names_player_power_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playergameresult',
            name='game_name',
        ),
        migrations.AlterField(
            model_name='playergameresult',
            name='game_number',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='playergameresult',
            name='round_number',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
