# Generated by Django 4.2.20 on 2025-05-21 22:51

from django.db import migrations, models
import django.db.models.deletion
import tournament.players
import tournament.wdd


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0149_remove_playergameresult_game_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WDDPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wdd_player_id', tournament.players.WDDPlayerIdField(unique=True, validators=[tournament.wdd.validate_wdd_player_id], verbose_name='WDD player id')),
                ('_wdd_firstname', models.CharField(blank=True, max_length=40)),
                ('_wdd_lastname', models.CharField(blank=True, max_length=40)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.player')),
            ],
        ),
    ]
