# Generated by Django 4.2.20 on 2025-05-21 22:52

from django.db import migrations


def add_wddplayers(apps, schema_editor):
    """Add WDDPlayers"""
    Player = apps.get_model('tournament', 'Player')
    WDDPlayer = apps.get_model('tournament', 'WDDPlayer')
    for p in Player.objects.filter(wdd_player_id__isnull=False):
        WDDPlayer.objects.create(wdd_player_id=p.wdd_player_id,
                                 player=p,
                                 _wdd_firstname=p._wdd_firstname,
                                 _wdd_lastname=p._wdd_lastname)

def delete_wddplayers(apps, schema_editor):
    """Delete WDDPlayers"""
    WDDPlayer = apps.get_model('tournament', 'WDDPlayer')
    # Copy attributes back to the corresponding Player
    for wdd in WDDPlayer.objects.all():
        p = wdd.player
        p.wdd_player_id = wdd.wdd_player_id
        p._wdd_firstname = wdd._wdd_firstname
        p._wdd_lastname = wdd._wdd_lastname
    WDDPlayer.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0150_create_wddplayer'),
    ]

    operations = [
        migrations.RunPython(add_wddplayers, delete_wddplayers)
    ]
