# Generated by Django 4.2.20 on 2025-05-21 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0151_auto_20250521_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='_wdd_firstname',
        ),
        migrations.RemoveField(
            model_name='player',
            name='_wdd_lastname',
        ),
        migrations.RemoveField(
            model_name='player',
            name='wdd_player_id',
        ),
    ]
