# Generated by Django 4.2.20 on 2025-05-25 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0152_remove_player__wdd_firstname_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dbncoverage',
            options={'verbose_name': 'DBN coverage'},
        ),
        migrations.AlterModelOptions(
            name='wddplayer',
            options={'verbose_name': 'WDD player'},
        ),
    ]
