# Generated by Django 4.2.20 on 2026-01-10 03:37

from django.db import migrations, models
import tournament.models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0154_alter_round_scoring_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='scoring_system',
            field=models.CharField(choices=[('7Eleven', '7Eleven'), ('Bangkok', 'Bangkok'), ('Base 3', 'Base 3'), ('C-Diplo Namur', 'C-Diplo Namur'), ('CDiplo 100', 'CDiplo 100'), ('CDiplo 80', 'CDiplo 80'), ('Carnage 2023', 'Carnage 2023'), ('Carnage with dead equal', 'Carnage with dead equal'), ('Carnage with elimination order', 'Carnage with elimination order'), ('Center-count Carnage', 'Center-count Carnage'), ('Detour09', 'Detour09'), ('Draw size', 'Draw size'), ('Haight v1.0', 'Haight v1.0'), ('ManorCon', 'ManorCon'), ('ManorCon v2', 'ManorCon v2'), ('Maxonian', 'Maxonian'), ('OMG', 'OMG'), ('OpenTribute', 'OpenTribute'), ('Original ManorCon', 'Original ManorCon'), ('Ranked Classic', 'Ranked Classic'), ('Solo or bust', 'Solo or bust'), ('Southern Sun', 'Southern Sun'), ('Sum of Squares', 'Sum of Squares'), ('Summer Classic', 'Summer Classic'), ('Tribute', 'Tribute'), ('Whipping', 'Whipping'), ('World Classic', 'World Classic'), ('Your Draw Size (short games)', 'Your Draw Size (short games)'), ('Your Draw Size (unlimited games)', 'Your Draw Size (unlimited games)')], help_text='How to calculate a score for one game', max_length=40, validators=[tournament.models.validate_game_scoring_system], verbose_name='Game scoring system'),
        ),
    ]
