# Generated by Django 4.2.20 on 2026-01-18 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0155_alter_round_scoring_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='show_current_scores',
            field=models.BooleanField(default=True, help_text='Show "if all games ended now" scores rather than after-last-round scores'),
        ),
    ]
