# Generated by Django 4.2.20 on 2026-01-21 05:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import tournament.models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0157_alter_round_scoring_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('slug', tournament.models.NameSlugField()),
                ('board_count', models.PositiveSmallIntegerField(blank=True, help_text='number of games to be played in this pool. Must be set for all pools except one in a round', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('the_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.round')),
            ],
            options={
                'ordering': ['-board_count'],
            },
        ),
        migrations.AddField(
            model_name='game',
            name='pool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournament.pool'),
        ),
        migrations.AddField(
            model_name='roundplayer',
            name='pool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournament.pool'),
        ),
        migrations.AddConstraint(
            model_name='pool',
            constraint=models.UniqueConstraint(fields=('the_round', 'name'), name='unique_round_name'),
        ),
        migrations.AddConstraint(
            model_name='pool',
            constraint=models.UniqueConstraint(fields=('the_round', 'slug'), name='unique_round_slug'),
        ),
    ]
