# Generated by Django 4.2.20 on 2026-03-03 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0159_alter_round_scoring_system"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roundplayer",
            name="score",
            field=models.FloatField(
                default=0.0,
                help_text="If the tournament doesn't use round scores, this stores any sitting-out bonus for the round",
            ),
        ),
    ]
