# Generated by Django 4.2.20 on 2026-03-24 17:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0161_alter_round_scoring_system"),
    ]

    operations = [
        migrations.AddField(
            model_name="pool",
            name="determines_top_rankings",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="this specifies how many best rankings will come from the pool. For a top board pool where the pool winner wins the tournament, set this",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddField(
            model_name="pool",
            name="game_score_multiplier",
            field=models.FloatField(
                blank=True,
                help_text="game score in this pool will be multiplied by this value, if specified",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pool",
            name="power_assignment",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A", "Minimising playing the same power"),
                    ("M", "Manually by TD or at the board"),
                    ("P", "Using player preferences and ranking"),
                ],
                help_text="overrides tournament setting if set",
                max_length=1,
                verbose_name="How powers are assigned",
            ),
        ),
        migrations.AddConstraint(
            model_name="pool",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("power_assignment", ""),
                    ("power_assignment__in", ["A", "M", "P"]),
                    _connector="OR",
                ),
                name="pool_power_assignment_valid",
            ),
        ),
    ]
