# Generated by Django 4.2.20 on 2026-03-24 18:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0162_pool_determines_top_rankings_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameplayer",
            name="tie_break_rank",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="If all players have the same score, what rank does this player get?",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddConstraint(
            model_name="gameplayer",
            constraint=models.UniqueConstraint(
                fields=("game", "tie_break_rank"), name="unique_game_tie_break"
            ),
        ),
    ]
