# Generated by Django 4.2.20 on 2026-03-24 23:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0163_gameplayer_tie_break_rank_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="num_games_in_team_score",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text='The number of game scores that contribute. If the team has more, the lowest will be dropped. Blank means "all"',
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddConstraint(
            model_name="tournament",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("team_size__isnull", False),
                    ("num_games_in_team_score__isnull", True),
                    _connector="OR",
                ),
                name="tournament_team_scoring_set_only_if_team_size_set",
            ),
        ),
    ]
