# Generated by Django 5.2.15 on 2026-06-25 01:37

import tournament.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0167_alter_round_scoring_system"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="name",
            field=models.CharField(
                help_text="Year will be appended based on start date",
                max_length=60,
                validators=[tournament.models.validate_no_newlines],
            ),
        ),
    ]
