# Generated by Django 5.2.15 on 2026-07-18 17:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0170_alter_round_scoring_system"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="num_games_in_team_score",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text='The number of team round game scores that contribute. If the team has more, the lowest will be dropped. Blank means "all"',
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
