# Generated by Django 5.2.15 on 2026-07-28 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0172_alter_round_scoring_system"),
    ]

    operations = [
        migrations.AddField(
            model_name="playergameresult",
            name="is_top_board",
            field=models.BooleanField(
                default=False, help_text="Whether this game was on a top board"
            ),
        ),
    ]
