# Generated by Django 5.2.15 on 2026-07-28 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0173_playergameresult_is_top_board"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="default_game_set",
            field=models.ForeignKey(
                blank=True,
                help_text="Default GameSet used when seeding games for rounds",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="tournament.gameset",
            ),
        ),
    ]
