# Generated by Django 5.2.15 on 2026-07-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0174_tournament_default_game_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplayer',
            name='calculated_score',
            field=models.FloatField(default=0.0, help_text='Score as calculated by the system'),
        ),
        migrations.AddField(
            model_name='roundplayer',
            name='calculated_score',
            field=models.FloatField(default=0.0, help_text='Score as calculated by the system'),
        ),
        migrations.AddField(
            model_name='team',
            name='calculated_score',
            field=models.FloatField(default=0.0, help_text='Score as calculated by the system'),
        ),
        migrations.AddField(
            model_name='tournamentplayer',
            name='calculated_score',
            field=models.FloatField(default=0.0, help_text='Score as calculated by the system'),
        ),
        migrations.AlterField(
            model_name='gameplayer',
            name='score',
            field=models.FloatField(default=0.0, help_text="Player's score for this game"),
        ),
        migrations.AlterField(
            model_name='team',
            name='score',
            field=models.FloatField(default=0.0, help_text='Score for the team'),
        ),
        migrations.AlterField(
            model_name='tournamentplayer',
            name='score',
            field=models.FloatField(default=0.0, help_text="Player's score for the tournament as a whole"),
        ),
    ]
