# Generated by Django 5.2.15 on 2026-07-31 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0175_gameplayer_calculated_score_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gameimage",
            options={},
        ),
        migrations.AlterModelOptions(
            name="supplycentreownership",
            options={},
        ),
    ]
