# Generated by Django 5.2.15 on 2026-08-05 18:13

from django.db import migrations


def _update_one_model(model_name):
    model = apps.get_model("tournament", model_name)
    for row in model.objects.all():
        row.calculated_score = row.score
        row.save(update_fields=["calculated_score"])

def set_calculated_score(apps, schema_editor):
    """Set calculated_score equal to score"""
    # Previously, the system (or user) set score
    # Now, the system sets calculated_score
    # If they don't match, the system will not update score
    # and it will use score as the actual score
    _update_one_model("GamePlayer")
    _update_one_model("RoundPlayer")
    _update_one_model("TournamentPlayer")
    _update_one_model("Team")

class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0176_alter_gameimage_options_and_more"),
    ]

    operations = []
