# Generated by Django 5.2.15 on 2026-08-09 06:08

import django.db.models.deletion
import tournament.circuits
import tournament.models
import tournament.wdd
import tournament.wdr
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0177_auto_20260805_1113"),
    ]

    operations = [
        migrations.CreateModel(
            name="Circuit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                (
                    "scoring_system",
                    models.CharField(
                        choices=[
                            (
                                "Sum best 3 tournament percentiles",
                                "Sum best 3 tournament percentiles",
                            )
                        ],
                        help_text="How to combine tournament scores into a circuit score",
                        max_length=40,
                        validators=[
                            tournament.circuits.validate_circuit_scoring_system
                        ],
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "wdd_circuit_id",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Add this after the circuit has been added to the WDD",
                        null=True,
                        validators=[tournament.wdd.validate_wdd_circuit_id],
                        verbose_name="This circuit's id in the World Diplomacy Database",
                    ),
                ),
                (
                    "wdr_circuit_id",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Add this after the circuit has been added to the WDR",
                        null=True,
                        validators=[tournament.wdr.validate_wdr_circuit_id],
                        verbose_name="This circuit's id in the World Diplomacy Reference",
                    ),
                ),
                (
                    "tournaments",
                    models.ManyToManyField(blank=True, to="tournament.tournament"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CircuitPlayer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField(default=0.0)),
                (
                    "circuit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tournament.circuit",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tournament.player",
                    ),
                ),
                (
                    "tournamentplayers",
                    models.ManyToManyField(
                        blank=True, to="tournament.tournamentplayer"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CircuitSeries",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("description", models.CharField(max_length=2000, null=True)),
                ("slug", tournament.models.NameSlugField(unique=True)),
                (
                    "circuits",
                    models.ManyToManyField(blank=True, to="tournament.circuit"),
                ),
            ],
            options={
                "verbose_name_plural": "Circuit Series",
            },
        ),
        migrations.AddConstraint(
            model_name="circuit",
            constraint=models.UniqueConstraint(
                fields=("name", "start_date"), name="circuit_unique_name_date"
            ),
        ),
        migrations.AddConstraint(
            model_name="circuitplayer",
            constraint=models.UniqueConstraint(
                fields=("player", "circuit"), name="unique_player_circuit"
            ),
        ),
    ]
