# Generated by Django 5.2.15 on 2026-08-14 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0178_circuit_circuitplayer_circuitseries_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="circuitseries",
            name="name",
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name="series",
            name="name",
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AddConstraint(
            model_name="circuit",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_date__gte", models.F("start_date"))),
                name="circuit_starts_before_end",
            ),
        ),
    ]
