# Generated by Django 5.2.15 on 2026-08-15 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0179_alter_circuitseries_name_alter_series_name_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PlayerTournamentRanking",
            new_name="PlayerEventRanking",
        ),
    ]
