# Generated by Django 5.2.15 on 2026-08-15 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0180_rename_playertournamentranking_playereventranking"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="playeraward",
            name="unique_player_tournament_date_name",
        ),
        migrations.RemoveConstraint(
            model_name="playereventranking",
            name="unique_player_tournament_year",
        ),
        migrations.RemoveConstraint(
            model_name="playergameresult",
            name="unique_names_player_power",
        ),
        migrations.RenameField(
            model_name="playeraward",
            old_name="tournament",
            new_name="event_name",
        ),
        migrations.RenameField(
            model_name="playereventranking",
            old_name="tournament",
            new_name="event_name",
        ),
        migrations.RenameField(
            model_name="playergameresult",
            old_name="tournament_name",
            new_name="event_name",
        ),
        migrations.AddConstraint(
            model_name="playeraward",
            constraint=models.UniqueConstraint(
                fields=("player", "event_name", "date", "name"),
                name="unique_player_event_name_date_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="playereventranking",
            constraint=models.UniqueConstraint(
                fields=("player", "event_name", "year"),
                name="unique_player_event_name_year",
            ),
        ),
        migrations.AddConstraint(
            model_name="playergameresult",
            constraint=models.UniqueConstraint(
                fields=("event_name", "round_number", "game_number", "player", "power"),
                name="unique_names_player_power",
            ),
        ),
    ]
