# Generated by Django 5.2.15 on 2026-08-22 17:54

import datetime
from django.db import migrations, models


def populate_missing_dates(apps, schema_editor):
    PlayerEventRanking = apps.get_model("tournament", "PlayerEventRanking")
    for ranking in PlayerEventRanking.objects.filter(date__isnull=True).iterator():
        ranking.date = datetime.date(ranking.year, 1, 1)
        ranking.save(update_fields=["date"])


class Migration(migrations.Migration):

    dependencies = [
        (
            "tournament",
            "0181_remove_playeraward_unique_player_tournament_date_name_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(populate_missing_dates, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name="playereventranking",
            name="unique_player_event_name_year",
        ),
        migrations.RemoveField(
            model_name="playereventranking",
            name="year",
        ),
        migrations.AlterField(
            model_name="playereventranking",
            name="date",
            field=models.DateField(default=datetime.datetime(1970, 1, 1, 0, 0)),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="playereventranking",
            constraint=models.UniqueConstraint(
                fields=("player", "event_name", "date"),
                name="unique_player_event_name_date",
            ),
        ),
    ]
