# Generated by Django 5.2.15 on 2026-08-23 00:22

from django.db import migrations, models
from django.db.models import Count


def assert_no_duplicate_playeraward_keys(apps, schema_editor):
    PlayerAward = apps.get_model("tournament", "PlayerAward")
    duplicate = (
        PlayerAward.objects.values("player_id", "event_ranking_id", "name")
        .annotate(num=Count("id"))
        .filter(num__gt=1)
        .order_by("player_id", "event_ranking_id", "name")
        .first()
    )
    if duplicate is not None:
        raise RuntimeError(
            "Cannot enforce unique_player_eventranking_name: duplicate PlayerAward rows exist "
            f"for player_id={duplicate['player_id']}, "
            f"event_ranking_id={duplicate['event_ranking_id']}, "
            f"name={duplicate['name']!r}."
        )


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0183_player_award_playergameresult_event_ranking"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="playeraward",
            name="unique_player_eventranking_date_name",
        ),
        migrations.RemoveField(
            model_name="playeraward",
            name="date",
        ),
        migrations.RemoveField(
            model_name="playeraward",
            name="wdd_tournament_id",
        ),
        migrations.RemoveField(
            model_name="playeraward",
            name="wdr_tournament_id",
        ),
        migrations.RemoveField(
            model_name="playergameresult",
            name="date",
        ),
        migrations.RemoveField(
            model_name="playergameresult",
            name="wdd_tournament_id",
        ),
        migrations.RemoveField(
            model_name="playergameresult",
            name="wdr_tournament_id",
        ),
        migrations.RunPython(assert_no_duplicate_playeraward_keys, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="playeraward",
            constraint=models.UniqueConstraint(
                fields=("player", "event_ranking", "name"),
                name="unique_player_eventranking_name",
            ),
        ),
    ]
