# Generated by Django 5.2.15 on 2026-08-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0184_remove_playeraward_unique_player_eventranking_date_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="playereventranking",
            name="event_kind",
            field=models.CharField(choices=[("T", "Tournament"), ("L", "League"), ("C", "Circuit"), ("O", "Other")], default="T", help_text="Kind of event (tournament, league, circuit)", max_length=1),
        ),
        migrations.AddField(
            model_name="playereventranking",
            name="tournament_kind",
            field=models.CharField(blank=True, help_text="Type of tournament on WDR/WDD", max_length=20, null=True),
        ),
    ]
