# Generated by Django 5.2.15 on 2026-08-25 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0187_awardrecipient_remove_tournamentplayer_awards'),
    ]

    operations = [
        migrations.AddField(
            model_name='awardrecipient',
            name='game',
            field=models.ForeignKey(blank=True, help_text='Set if this award is for something that happened in a specific Game', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournament.game'),
        ),
    ]
