# Generated by Django 5.2.15 on 2026-09-01 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0188_awardrecipient_game'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playereventranking',
            old_name='position',
            new_name='rank',
        ),
        migrations.RenameField(
            model_name='playergameresult',
            old_name='position',
            new_name='rank',
        ),
        migrations.RenameField(
            model_name='playergameresult',
            old_name='position_equals',
            new_name='rank_equals',
        ),
    ]
