# Generated by Django 5.2.15 on 2026-09-02 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0192_alter_round_scoring_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='calculated_rank',
            field=models.PositiveSmallIntegerField(default=0, help_text='Rank as calculated by the system'),
        ),
        migrations.AddField(
            model_name='team',
            name='rank_override',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Official rank override', null=True),
        ),
        migrations.AddField(
            model_name='tournamentplayer',
            name='calculated_rank',
            field=models.PositiveSmallIntegerField(default=0, help_text='Rank as calculated by the system'),
        ),
        migrations.AddField(
            model_name='tournamentplayer',
            name='rank_override',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Official rank override', null=True),
        ),
    ]
