# Generated by Django 5.2.15 on 2026-09-08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0193_team_calculated_rank_team_rank_override_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='rank_override',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Official rank override', null=True, validators=[django.core.validators.MaxValueValidator(32766)]),
        ),
        migrations.AlterField(
            model_name='tournamentplayer',
            name='rank_override',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Official rank override', null=True, validators=[django.core.validators.MaxValueValidator(32766)]),
        ),
    ]