# Generated by Django 5.2.15 on 2026-09-08

from operator import itemgetter

from django.db import migrations


UNRANKED = 32767


def add_ranks(to_scores, start=1):
    """Return competition ranks for a dict of scores."""
    result = {}
    last_score = None
    for i, (key, score) in enumerate(sorted(to_scores.items(), key=itemgetter(1), reverse=True),
                                     start=start):
        if score != last_score:
            place, last_score = i, score
        result[key] = (place, score)
    return result


def tournament_player_ranks(tournament, TournamentPlayer, Pool, GamePlayer):
    """Calculate stored TournamentPlayer ranks from stored scores."""
    top_pool = Pool.objects.filter(the_round__tournament=tournament,
                                   determines_top_rankings__isnull=False).first()
    tournament_players = list(TournamentPlayer.objects.filter(tournament=tournament).order_by('id'))
    scores = {tp.player_id: tp.score for tp in tournament_players}
    unranked_player_ids = {tp.player_id for tp in tournament_players if tp.unranked}
    result = {}

    for player_id in unranked_player_ids:
        result[player_id] = (UNRANKED, scores.pop(player_id))

    rank = 1
    if top_pool is not None:
        top_gameplayers = GamePlayer.objects.filter(game__pool=top_pool).order_by('-score',
                                                                                  'tie_break_rank')
        last_score = None
        i = 0
        for gp in top_gameplayers:
            if gp.player_id in unranked_player_ids:
                continue
            i += 1
            if (gp.score != last_score) or (gp.tie_break_rank is not None):
                rank, last_score = i, gp.score
                if rank > top_pool.determines_top_rankings:
                    break
            if gp.player_id in scores:
                result[gp.player_id] = (rank, scores.pop(gp.player_id))

    result.update(add_ranks(scores, rank))
    return result


def backfill_calculated_ranks(apps, schema_editor):
    Tournament = apps.get_model('tournament', 'Tournament')
    TournamentPlayer = apps.get_model('tournament', 'TournamentPlayer')
    Team = apps.get_model('tournament', 'Team')
    Pool = apps.get_model('tournament', 'Pool')
    GamePlayer = apps.get_model('tournament', 'GamePlayer')

    for tournament in Tournament.objects.all():
        ranks = tournament_player_ranks(tournament, TournamentPlayer, Pool, GamePlayer)
        tournament_players = list(TournamentPlayer.objects.filter(tournament=tournament).order_by('id'))
        for tournament_player in tournament_players:
            tournament_player.calculated_rank = ranks[tournament_player.player_id][0]
        TournamentPlayer.objects.bulk_update(tournament_players, ['calculated_rank'])

        teams = list(Team.objects.filter(tournament=tournament).order_by('id'))
        team_ranks = add_ranks({team.id: team.score for team in teams})
        for team in teams:
            team.calculated_rank = team_ranks[team.id][0]
        Team.objects.bulk_update(teams, ['calculated_rank'])


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0194_alter_team_rank_override_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_calculated_ranks, migrations.RunPython.noop),
    ]