name: Parser Sites Live Integration

on:
  schedule:
    - cron: '47 3 * * *'
  workflow_dispatch:

jobs:
  live-parser-sites:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Set up Python 3.12
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: Run Live Parser Tests
        run: |
          cd visualiser
          python ./manage.py test \
            --tag=wikipedia_live \
            --tag=backstabbr \
            --tag=webdip \
            --tag=wdr \
            --tag=wdd
